import { describe, expect, it } from 'vitest';
import { AutoresearchRunner, blankLoopSnapshot, canConnectStage, defaultLoopConfig, loopFingerprint, restoreLoop, serializeLoop, validateLoop } from '../src/autoresearch';
import { lenses } from '../src/data';
import { ApiError } from '../src/api';
import type { ExecuteRequest, ExecuteResponse } from '../shared/contracts';
const lens=lenses[0];const inputs={reader:lens.replay.reader,overlap:lens.replay.overlap,paper:lens.replay.paper,profile:lens.replay.profile};
function options(){return {lens,inputs,config:defaultLoopConfig(),mode:'live' as const,demoCode:'test-only-access',onUpdate:()=>{}};}
const response=(request:ExecuteRequest):ExecuteResponse=>({output:structuredClone(lens.replay[request.type]),usage:{requests:1,inputTokens:100,outputTokens:20},model:'test-model'});
describe('Autoresearch graph and bounds',()=>{
 it('requires the stage connections and rejects cycles and backwards wires',()=>{const config=defaultLoopConfig();expect(validateLoop(config)).toBe(null);expect(validateLoop({...config,edges:config.edges.slice(1)})).toMatch('Connect');expect(validateLoop({...config,edges:[...config.edges,{id:'bad',source:'revise',target:'propose'}]})).toMatch('Rounds control');expect(canConnectStage(config,'revise','propose')).toBe(false);expect(canConnectStage(config,'objective','critique')).toBe(false);expect(validateLoop({...config,rounds:4})).toMatch('1–3');expect(validateLoop({...config,stages:config.stages.slice(0,3)})).toMatch('Revise');});
 it('allows a single pass without the revision stage',()=>{const config=defaultLoopConfig();expect(validateLoop({...config,rounds:1,stages:config.stages.slice(0,3),edges:config.edges.slice(0,2)})).toBe(null);});
 it('runs 3 rounds as six serial requests using one run ID and preceding critique',async()=>{let active=0,peak=0;const requests:ExecuteRequest[]=[];const runner=new AutoresearchRunner(async request=>{active++;peak=Math.max(peak,active);requests.push(request);await Promise.resolve();active--;return response(request);});const snapshot=await runner.run({...options(),config:{...defaultLoopConfig(),rounds:3}});expect(snapshot.status).toBe('complete');expect(snapshot.rounds).toHaveLength(3);expect(requests.map(r=>r.type)).toEqual(['proposer','skeptic','proposer','skeptic','proposer','skeptic']);expect(new Set(requests.map(r=>r.runId)).size).toBe(1);expect(peak).toBe(1);expect(requests[2].inputs.autoresearch_previous_critique.critique).toBeDefined();expect(requests[2].inputs.autoresearch_previous_proposal.proposals).toHaveLength(1);expect(requests[3].inputs.autoresearch_previous_proposal).toBeUndefined();expect(Object.values(requests[3].inputs).flatMap(a=>a.proposals??[])).toHaveLength(1);expect(snapshot.usage).toEqual({requests:6,inputTokens:600,outputTokens:120,unmeasuredRequests:0});});
 it('stops at an explicitly configured verdict',async()=>{const runner=new AutoresearchRunner(async request=>{const result=response(request);if(result.output.critique)result.output.critique.verdict='supported';return result;});const snapshot=await runner.run({...options(),config:{...defaultLoopConfig(),rounds:3,stopOnSupported:true}});expect(snapshot.rounds).toHaveLength(1);expect(snapshot.dispatches).toBe(2);expect(snapshot.stopReason).toContain('supported');});
 it('refuses missing grounding and never substitutes recorded artifacts in Live',async()=>{let count=0;const runner=new AutoresearchRunner(async request=>{count++;return response(request);});await expect(runner.run({...options(),inputs:{}})).rejects.toThrow('Reader');expect(count).toBe(0);});
 it('Replay uses one authored incremental review with no inference',async()=>{const runner=new AutoresearchRunner(async()=>{throw new Error('should not call');});const snapshot=await runner.run({...options(),mode:'replay'});expect(snapshot.rounds).toHaveLength(1);expect(snapshot.usage.requests).toBe(0);expect(snapshot.stopReason).toContain('Recorded');await expect(runner.run({...options(),mode:'replay',lens:{...lens,paper:{...lens.paper,id:'pasted-paper'}}})).rejects.toThrow('bundled paper');await expect(runner.run({...options(),mode:'replay',config:{...defaultLoopConfig(),kind:'speculative'}})).rejects.toThrow('recorded review');});
});
describe('Autoresearch cancellation, resume and persistence',()=>{
 it('cancelled late output cannot overwrite a new run',async()=>{let release!:(value:ExecuteResponse)=>void;let started!:()=>void;const ready=new Promise<void>(resolve=>started=resolve);const runner=new AutoresearchRunner(async()=>{started();return new Promise(resolve=>release=resolve);});const updates:string[]=[];const old=runner.run({...options(),onUpdate:s=>updates.push(s.status)});await ready;runner.cancel();const fresh=await runner.run({...options(),mode:'replay',onUpdate:s=>updates.push(s.status)});const count=updates.length;release({output:{summary:'late model output'},usage:{requests:1,inputTokens:1,outputTokens:1},model:'test'});const cancelled=await old;expect(updates.length).toBe(count);expect(cancelled.status).toBe('paused');expect(cancelled.rounds).toHaveLength(0);expect(fresh.rounds).toHaveLength(1);});
 it('keeps interrupted usage unknown; resumes with the saved proposal instead of rebilling it',async()=>{let count=0;let started!:()=>void;const ready=new Promise<void>(resolve=>started=resolve);const runner=new AutoresearchRunner(async(request,_code,signal)=>{count++;if(count===2){started();return new Promise((_,reject)=>signal?.addEventListener('abort',()=>reject(new DOMException('cancelled','AbortError'))));}return response(request);});const running=runner.run(options());await ready;runner.cancel();const paused=await running;expect(paused.pending?.proposals).toHaveLength(3);expect(paused.usage).toEqual({requests:2,inputTokens:100,outputTokens:20,unmeasuredRequests:1});const requests:ExecuteRequest[]=[];const resumed=await new AutoresearchRunner(async request=>{requests.push(request);return response(request);}).run({...options(),snapshot:paused});expect(requests[0].type).toBe('skeptic');expect(requests).toHaveLength(3);expect(resumed.rounds).toHaveLength(2);expect(resumed.runId).toBe(paused.runId);expect(resumed.usage.requests).toBe(5);expect(resumed.usage.unmeasuredRequests).toBe(1);});
 it('does not retry automatically and does not count an authentication refusal as inference',async()=>{let calls=0;const runner=new AutoresearchRunner(async()=>{calls++;throw new ApiError('Denied',401);});const snapshot=await runner.run(options());expect(calls).toBe(1);expect(snapshot.status).toBe('error');expect(snapshot.usage.requests).toBe(0);expect(snapshot.dispatches).toBe(1);});
 it('retains the dispatch ceiling across manual resumes',async()=>{const opts=options();const snapshot=blankLoopSnapshot(loopFingerprint(lens,inputs,opts.config,'live'),'live');snapshot.dispatches=8;let calls=0;const result=await new AutoresearchRunner(async request=>{calls++;return response(request);}).run({...opts,snapshot});expect(calls).toBe(0);expect(result.status).toBe('error');expect(result.stopReason).toContain('Eight-request');});
 it('restores interrupted work as paused and never serializes access-code properties',()=>{const config=defaultLoopConfig();const snapshot=blankLoopSnapshot(loopFingerprint(lens,inputs,config,'live'),'live');snapshot.status='running';const raw=serializeLoop(Object.assign(config,{demoCode:'SECRET'}),Object.assign(snapshot,{demoCode:'SECRET'}));expect(raw).not.toContain('SECRET');expect(raw).not.toContain('demoCode');expect(restoreLoop(raw)?.snapshot?.status).toBe('paused');expect(restoreLoop('{malformed')).toBe(null);expect(restoreLoop(JSON.stringify({version:1,config:{},snapshot:null}))).toBe(null);});
 it('changing the objective invalidates Resume; moving a stage preserves it',async()=>{const config=defaultLoopConfig();const fp=loopFingerprint(lens,inputs,config,'live');expect(loopFingerprint(lens,inputs,{...config,stages:config.stages.map(s=>({...s,position:{x:100,y:200}}))},'live')).toBe(fp);const snapshot=blankLoopSnapshot(fp,'live');await expect(new AutoresearchRunner().run({...options(),config:{...config,objective:'Changed objective'},snapshot})).rejects.toThrow('changed');});
});
