import { describe,it,expect,afterEach,vi } from 'vitest';
import { Responses } from 'openai/resources/responses/responses';
import { createApp } from '../server/index';
import { zodTextFormat } from 'openai/helpers/zod';
import { outputSchemas } from '../server/validation';
import { lenses } from '../src/data';
import type { ExecuteRequest } from '../shared/contracts';
const fixture=lenses[0];
const request:ExecuteRequest={runId:'test-run',nodeId:'reader',type:'reader',paper:fixture.paper,profile:fixture.profile,settings:{},inputs:{}};
const fakeResponse={status:'completed',output_text:JSON.stringify(fixture.replay.reader),usage:{input_tokens:101,output_tokens:47}};
const servers:ReturnType<ReturnType<typeof createApp>['listen']>[]=[];
const code='test-demo-code-only';
async function server(){const flag=process.env.MARGINALIA_PREGENERATE;process.env.MARGINALIA_PREGENERATE='1';const oldKey=process.env.OPENAI_API_KEY,oldCode=process.env.DEMO_CODE;process.env.OPENAI_API_KEY='test-not-a-real-key';process.env.DEMO_CODE=code;const app=createApp();if(flag===undefined)delete process.env.MARGINALIA_PREGENERATE;else process.env.MARGINALIA_PREGENERATE=flag;if(oldKey===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=oldKey;if(oldCode===undefined)delete process.env.DEMO_CODE;else process.env.DEMO_CODE=oldCode;const s=app.listen(0,'127.0.0.1');servers.push(s);await new Promise<void>((resolve,reject)=>{s.once('listening',resolve);s.once('error',reject);});return `http://127.0.0.1:${(s.address() as {port:number}).port}`;}
async function execute(base:string,body=request,auth=code){return fetch(base+'/api/execute-node',{method:'POST',headers:{'content-type':'application/json','X-Demo-Code':auth},body:JSON.stringify(body)});}
afterEach(async()=>{vi.restoreAllMocks();await Promise.all(servers.splice(0).map(s=>new Promise<void>(resolve=>{s.closeAllConnections();s.close(()=>resolve());})))});
describe('Live transport and quotas (mocked OpenAI; no paid calls)',()=>{
 it('produces strict object schemas for every runtime specialist',()=>{
  function check(value:any){if(!value||typeof value!=='object')return;if(value.type==='object'){expect(value.additionalProperties).toBe(false);expect((value.required??[]).sort()).toEqual(Object.keys(value.properties??{}).sort());}Object.values(value).forEach(check);}
  for(const [type,schema]of Object.entries(outputSchemas)){const format=zodTextFormat(schema,type);expect(format.strict).toBe(true);check(format.schema);}
 });
 it('uses strict Responses output, server-chosen model and measured tokens',async()=>{
  const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue(fakeResponse as never);const base=await server();
  const response=await execute(base);expect(response.status).toBe(200);const data=await response.json();expect(data.usage).toEqual({requests:1,inputTokens:101,outputTokens:47});expect(data.output.claims.length).toBeGreaterThan(0);
  const args=spy.mock.calls[0][0] as any;expect(args.model).toBe(process.env.OPENAI_MODEL_FAST||'gpt-5.4-mini');expect(args.text.format.strict).toBe(true);expect(args.store).toBe(false);expect(args.reasoning.effort).toBe('low');
 });
 it('rejects guests before any model request',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue(fakeResponse as never);const base=await server();expect((await execute(base,request,'wrong')).status).toBe(401);expect(spy).not.toHaveBeenCalled();});
 it('rejects retired comment analysis before a model request',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue(fakeResponse as never);const base=await server();const comment={uri:'at://did:plc:test/app.bsky.feed.post/old',cid:'old',authorDid:'did:plc:test',authorHandle:'legacy.test',displayName:'Legacy',text:'Obsolete saved discussion',createdAt:'2026-10-06T00:00:00Z',url:'https://bsky.app/profile/legacy.test/post/old',matchType:'possible-mention' as const,matchedIdentifier:'',parentUri:null,retrievedAt:'2026-10-06T00:00:00Z'};for(const body of [{...request,settings:{selectedComment:comment}},{...request,inputs:{legacy:{summary:'Old discussion',posts:[comment]}}}]){const response=await execute(base,body);expect(response.status).toBe(400);expect((await response.json()).error).toContain('comment analysis has been removed');}expect(spy).not.toHaveBeenCalled();});
 it('allows unsupported paper mechanisms to decline an illustration honestly',async()=>{vi.spyOn(Responses.prototype,'create').mockResolvedValue({...fakeResponse,output_text:JSON.stringify({summary:'No compatible illustration is implemented for the supplied mechanism.',demo:null})} as never);const base=await server();const response=await execute(base,{...request,type:'demonstrator',inputs:{reader:fixture.replay.reader}});expect(response.status).toBe(200);const data=await response.json();expect(data.output.demo).toBeUndefined();expect(data.output.summary).toContain('No compatible');});
 it('marks missing usage as unmeasured instead of claiming zero billed tokens',async()=>{vi.spyOn(Responses.prototype,'create').mockResolvedValue({...fakeResponse,usage:undefined} as never);const base=await server();const data=await execute(base).then(r=>r.json());expect(data.usage.unmeasuredRequests).toBe(1);});
 it('chooses the reasoning model for evidence-backed synthesis',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue({...fakeResponse,output_text:JSON.stringify(fixture.replay.overlap)} as never);const base=await server();const response=await execute(base,{...request,type:'overlap',inputs:{reader:fixture.replay.reader}});expect(response.status).toBe(200);const args=spy.mock.calls[0][0] as any;expect(args.model).toBe(process.env.OPENAI_MODEL_REASONING||'gpt-5.4');expect(args.reasoning.effort).toBe('medium');});
 it('releases request slots after provider failures and leaves Replay available',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockRejectedValueOnce(new Error('provider unavailable')).mockResolvedValue(fakeResponse as never);const base=await server();const failed=await execute(base);expect(failed.status).toBe(502);const error=await failed.json();expect(error.error).toContain('recorded example');expect(error.tokenUsageAvailable).toBe(false);expect(error.requests).toBe(1);expect((await execute(base)).status).toBe(200);expect(spy).toHaveBeenCalledTimes(2);});
 it('caps each run at eight requests',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue(fakeResponse as never);const base=await server();for(let i=0;i<8;i++)expect((await execute(base)).status).toBe(200);expect((await execute(base)).status).toBe(429);expect(spy).toHaveBeenCalledTimes(8);});
 it('rejects ungrounded output without silently retrying',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue({...fakeResponse,output_text:JSON.stringify({summary:'Bad result',claims:[{id:'c',text:'made up',limitations:[],evidenceRefs:[{documentId:'fake',passageId:'none',supportingExcerpt:'fabricated'}]}],method:'none',limitations:[]})} as never);const base=await server();expect((await execute(base)).status).toBe(502);expect(spy).toHaveBeenCalledTimes(1);});
 it('allows only two simultaneous model requests',async()=>{let finish!:()=>void;const waiting=new Promise<any>(resolve=>{finish=()=>resolve(fakeResponse);});const spy=vi.spyOn(Responses.prototype,'create').mockImplementation(()=>waiting as never);const base=await server();const one=execute(base);const two=execute(base);await vi.waitFor(()=>expect(spy).toHaveBeenCalledTimes(2));expect((await execute(base)).status).toBe(429);finish();expect((await one).status).toBe(200);expect((await two).status).toBe(200);});
});
