import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {applyGoMove,emptyGoPosition,exportMainlineSgf,goBoardKey,goCoordinate,goGroup,parseSgfMainline,replayGoGame,type GoColor,type GoGame} from '../src/go';
const collection=JSON.parse(readFileSync(new URL('../public/alphago/games.json',import.meta.url),'utf8')) as {games:GoGame[]};
function setStones(size:number,black:[number,number][],white:[number,number][],nextColor:GoColor='B'){
 const position=emptyGoPosition(size);position.nextColor=nextColor;for(const [color,coordinates]of [['B',black],['W',white]] as const)for(const [x,y]of coordinates)position.stones[y*size+x]={color,moveNumber:1};return position;
}
describe('Go captures and legality',()=>{
 it('removes an entire adjacent group after its final liberty closes',()=>{const position=setStones(5,[[0,1],[2,1],[0,2],[2,2],[1,3]],[[1,1],[1,2]]);expect(goGroup(position.stones,6,5).liberties).toEqual([1]);const next=applyGoMove(position,{color:'B',x:1,y:0});expect(next.captures.B).toBe(2);expect(next.stones[6]).toBe(null);expect(next.stones[11]).toBe(null);expect(position.stones[6]?.color).toBe('W');});
 it('rejects occupied intersections, out of bounds, wrong color and suicide',()=>{const position=setStones(5,[],[[0,1],[2,1],[1,0],[1,2]]);expect(()=>applyGoMove(position,{color:'B',x:1,y:1})).toThrow('suicide');expect(()=>applyGoMove(position,{color:'B',x:0,y:1})).toThrow('occupied');expect(()=>applyGoMove(position,{color:'B',x:5,y:0})).toThrow('coordinate');expect(()=>applyGoMove(position,{color:'W',x:4,y:4})).toThrow('expected B');});
 it('allows a capture that creates liberties for the played stone',()=>{const position=setStones(3,[[0,0],[2,0],[0,2],[2,2]],[[0,1],[2,1],[1,0],[1,2]]);const next=applyGoMove(position,{color:'B',x:1,y:1});expect(next.captures.B).toBe(4);expect(goGroup(next.stones,4,3).liberties).toHaveLength(4);});
 it('rejects immediate ko recapture',()=>{const before=setStones(5,[[1,1],[2,0],[3,1],[2,2]],[[0,1],[1,0],[1,2]],'W');const after=applyGoMove(before,{color:'W',x:2,y:1});expect(after.captures.W).toBe(1);expect(()=>applyGoMove(after,{color:'B',x:1,y:1},goBoardKey(before))).toThrow('ko');});
 it('handles passes without placing stones and maps coordinates without I',()=>{const positions=replayGoGame({size:19,moves:[{color:'B',x:null,y:null},{color:'W',x:null,y:null}]});expect(positions).toHaveLength(3);expect(positions[2].stones.every(s=>s===null)).toBe(true);expect(positions[2].nextColor).toBe('B');expect(goCoordinate({color:'B',x:8,y:0})).toBe('J19');expect(goCoordinate({color:'W',x:null,y:null})).toBe('pass');});
});
describe('SGF played-mainline extraction',()=>{
 it('handles escaped property text and skips alternate variations and commentary',()=>{const parsed=parseSgfMainline('(;GM[1]SZ[5]PB[Name\\]escaped]C[Comment ;B[aa\\] ignored];B[bb](;W[cc];B[dd])(;W[aa];B[ab]))');expect(parsed.metadata.PB).toBe('Name]escaped');expect(parsed.moves).toEqual([{color:'B',x:1,y:1},{color:'W',x:2,y:2},{color:'B',x:3,y:3}]);expect(JSON.stringify(parsed)).not.toContain('Comment');});
 it('supports empty and legacy tt passes but rejects setup positions and malformed records',()=>{expect(parseSgfMainline('(;SZ[19];B[];W[tt])').moves.every(m=>m.x===null)).toBe(true);expect(()=>parseSgfMainline('(;SZ[19]AB[aa];W[bb])')).toThrow('Setup');expect(()=>parseSgfMainline('(;SZ[19];B[zz])')).toThrow('coordinate');expect(()=>parseSgfMainline('(;SZ[19];B[aa]')).toThrow('Unclosed');});
});
describe('Five actual AlphaGo–Lee Sedol games',()=>{
 it('retains all played moves and recorded results, with a 4–1 match result',()=>{expect(collection.games.map(g=>g.moves.length)).toEqual([186,211,176,180,280]);expect(collection.games.map(g=>g.result)).toEqual(['W+Resign','B+Resign','W+Resign','W+Resign','W+Resign']);expect(collection.games.filter(g=>(g.result.startsWith('B')?g.black:g.white)==='AlphaGo')).toHaveLength(4);expect(collection.games.reduce((sum,g)=>sum+g.moves.length,0)).toBe(1033);});
 it.each(collection.games)('validates every played move and captures in game $number',game=>{const positions=replayGoGame(game);expect(positions).toHaveLength(game.moves.length+1);for(const p of positions){const passes=game.moves.slice(0,p.move).filter(move=>move.x===null).length;expect(p.stones.filter(Boolean).length).toBe(p.move-passes-p.captures.B-p.captures.W);for(let index=0;index<p.stones.length;index++)if(p.stones[index])expect(goGroup(p.stones,index,p.size).liberties.length).toBeGreaterThan(0);}const finalCaptures=[{B:4,W:3},{B:3,W:5},{B:4,W:6},{B:2,W:11},{B:14,W:18}];expect(positions.at(-1)?.captures).toEqual(finalCaptures[game.number-1]);});
 it('identifies the highlighted real moves',()=>{const move37=collection.games[1].moves[36];const move78=collection.games[3].moves[77];expect(move37.color).toBe('B');expect(goCoordinate(move37)).toBe('P10');expect(move78.color).toBe('W');expect(goCoordinate(move78)).toBe('L11');});
 it.each(collection.games)('game $number download is commentary-free, matches its hash and round-trips exactly',game=>{const text=readFileSync(new URL(`../public${game.downloadUrl}`,import.meta.url),'utf8');expect(text).toBe(exportMainlineSgf(game));expect(createHash('sha256').update(text).digest('hex')).toBe(game.normalizedSha256);expect(text).not.toMatch(/\b(?:C|TR|LB|SQ)\[/);expect((text.match(/\(/g)??[]).length).toBe(1);expect(parseSgfMainline(text).moves).toEqual(game.moves);});
});
