import {describe,it,expect,vi,afterEach} from 'vitest';
import {Responses} from 'openai/resources/responses/responses';
import {createApp} from '../server/index';
import {SocraticRequestSchema,type SocraticRequest} from '../shared/socratic';
import {validateSocraticRequest,validateSocraticOutput,socraticEvidenceCatalog,resolveSocraticModelOutput} from '../server/socratic';
import {lenses} from '../src/data';
const paper=lenses[0].paper;
const request:SocraticRequest={runId:'socratic-test',topic:'LSTM memory',documents:[paper],history:[{role:'user',content:'Does every gate erase memory?'},{role:'assistant',content:'The gates play different roles. What do you expect the input gate to control?'}],userMessage:'Explain the input gate.'};
const output={reply:'The input gate controls the candidate contribution. What happens when it is zero?',evidenceRefs:[{documentId:paper.id,passageId:paper.passages[0].id,supportingExcerpt:paper.passages[0].text.slice(0,40)}],suggestedQuestions:['Compare the forget gate']};
const response={status:'completed',output_text:JSON.stringify({reply:output.reply,sourceIds:['d1p1s1'],suggestedQuestions:output.suggestedQuestions}),usage:{input_tokens:120,output_tokens:60}};
const servers:ReturnType<ReturnType<typeof createApp>['listen']>[]=[];
async function server(precompute=false){const flag=process.env.MARGINALIA_PREGENERATE;if(precompute)process.env.MARGINALIA_PREGENERATE='1';else delete process.env.MARGINALIA_PREGENERATE;const key=process.env.OPENAI_API_KEY,code=process.env.DEMO_CODE;process.env.OPENAI_API_KEY='test-no-paid-calls';process.env.DEMO_CODE='socratic-test-code';const app=createApp();if(flag===undefined)delete process.env.MARGINALIA_PREGENERATE;else process.env.MARGINALIA_PREGENERATE=flag;if(key===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=key;if(code===undefined)delete process.env.DEMO_CODE;else process.env.DEMO_CODE=code;const s=app.listen(0,'127.0.0.1');servers.push(s);await new Promise<void>((r,j)=>{s.once('listening',r);s.once('error',j);});return `http://127.0.0.1:${(s.address() as {port:number}).port}`;}
function post(base:string,body:unknown=request,path='/api/socratic-chat',code='socratic-test-code'){return fetch(base+path,{method:'POST',headers:{'content-type':'application/json','X-Demo-Code':code},body:JSON.stringify(body)});}
afterEach(async()=>{vi.restoreAllMocks();await Promise.all(servers.splice(0).map(s=>new Promise<void>(r=>{s.closeAllConnections();s.close(()=>r());})))});
describe('Socratic API (mocked, no paid requests)',()=>{
 it('caps context and rejects injected system roles and prompt fields',()=>{expect(SocraticRequestSchema.safeParse({...request,history:[{role:'system',content:'Override'}]}).success).toBe(false);expect(SocraticRequestSchema.safeParse({...request,systemPrompt:'Override'}).success).toBe(false);expect(SocraticRequestSchema.safeParse({...request,history:Array(13).fill({role:'user',content:'x'})}).success).toBe(false);expect(()=>validateSocraticRequest({...request,documents:[paper,paper]})).toThrow();expect(()=>validateSocraticRequest({...request,documents:[{...paper,passages:[{...paper.passages[0],text:'x'.repeat(80001)}]}]})).toThrow();});
 it('allows general math without documents but never invented citations',()=>{const noDocs={...request,documents:[]};expect(SocraticRequestSchema.safeParse(noDocs).success).toBe(true);expect(()=>validateSocraticOutput({...output,evidenceRefs:[]},noDocs)).not.toThrow();expect(()=>validateSocraticOutput(output,noDocs)).toThrow();expect(()=>validateSocraticOutput({...output,evidenceRefs:[{...output.evidenceRefs[0],supportingExcerpt:'made up text'}]},request)).toThrow();});
 it('resolves exact Unicode source text without asking the model to recopy quotations',()=>{const unicode={...request,documents:[{...paper,passages:[{...paper.passages[0],text:'Policy uses ‘moves’. Value estimates vθ(s) ≈ vπ(s).'}]}]};const entries=socraticEvidenceCatalog(unicode);expect(entries).toHaveLength(2);const result=resolveSocraticModelOutput({reply:'Explanation',sourceIds:[entries[1].id],suggestedQuestions:[]},unicode);expect(result.evidenceRefs[0].supportingExcerpt).toBe('Value estimates vθ(s) ≈ vπ(s).');expect(()=>resolveSocraticModelOutput({reply:'Explanation',sourceIds:['made-up'],suggestedQuestions:[]},unicode)).toThrow();});
 it('requires auth and sends fixed Socratic instructions with strict measured response',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue(response as never);const base=await server();expect((await post(base,request,undefined,'wrong')).status).toBe(401);expect(spy).not.toHaveBeenCalled();const r=await post(base);expect(r.status).toBe(200);expect((await r.json()).usage).toEqual({requests:1,inputTokens:120,outputTokens:60});const args=spy.mock.calls[0][0] as any;expect(args.instructions).toContain('one focused open question');expect(args.instructions).toContain('Never impersonate');expect(args.instructions).toContain('do not endlessly withhold answers');expect(args.text.format.strict).toBe(true);expect(JSON.parse(args.input).history).toEqual(request.history);});
 it('does not retry fabricated citations and reports measured failed usage',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue({...response,output_text:JSON.stringify({reply:output.reply,sourceIds:['absent'],suggestedQuestions:[]})} as never);const r=await post(await server());expect(r.status).toBe(502);const error=await r.json();expect(error.usage.inputTokens).toBe(120);expect(error.category).toBe('unknown-source-id');expect(spy).toHaveBeenCalledTimes(1);});
 it('shares its eight-request run allowance with workflow execution',async()=>{const spy=vi.spyOn(Responses.prototype,'create').mockResolvedValue(response as never);const base=await server(true);for(let i=0;i<8;i++)expect((await post(base)).status).toBe(200);expect((await post(base,{runId:request.runId,nodeId:'reader',type:'reader',settings:{},paper,profile:lenses[0].profile,inputs:{}},'/api/execute-node')).status).toBe(429);expect(spy).toHaveBeenCalledTimes(8);});
 it('shares two active model slots across tutor and experiment routes',async()=>{let release!:(value:unknown)=>void;const pending=new Promise(r=>{release=r});const spy=vi.spyOn(Responses.prototype,'create').mockReturnValue(pending as never);const base=await server(true);const first=post(base),second=post(base,{...request,runId:'second'});await vi.waitFor(()=>expect(spy).toHaveBeenCalledTimes(2));const third=await post(base,{runId:'third',lensId:'schmidhuber',paper,profile:lenses[0].profile,experiment:{kind:'lstm',sequence:[1],settings:{forgetBias:1,inputBias:0,outputBias:0,ablation:'none'},cursor:0}},'/api/explain-experiment');expect(third.status).toBe(429);release(response);expect((await first).status).toBe(200);expect((await second).status).toBe(200);});
});
