import { describe,it,expect } from 'vitest';
import { lenses } from '../src/data';
import { advanceQuiz,buildStudyCards,followUp,safeUrl,studyFilename,studyMarkdown } from '../src/study';
describe('consolidation study',()=>{
 it.each(lenses)('exports source-backed cards for $id without inventing a recorded output',lens=>{const cards=buildStudyCards(lens);expect(cards.length).toBe(lens.paper.passages.length);for(const card of cards){expect(card.sources.length).toBeGreaterThan(0);expect(lens.paper.passages.some(p=>p.text===card.answer)).toBe(true);}const md=studyMarkdown(lens.paper.title,cards);expect(md).toContain('\n\n**Q:**');expect(md).toContain('\n\n**A:**');expect(md).toContain('PDF p.');expect(md).not.toContain('\\n');});
 it('uses provided outputs and excludes unresolved evidence',()=>{const lens=lenses[0];const cards=buildStudyCards(lens,{summary:'',claims:[{id:'new',text:'Fresh claim',limitations:[],evidenceRefs:[{documentId:lens.paper.id,passageId:lens.paper.passages[0].id,supportingExcerpt:'x'}]},{id:'bad',text:'Unresolved',limitations:[],evidenceRefs:[{documentId:'missing',passageId:'none',supportingExcerpt:'x'}]}]});expect(cards.map(c=>c.answer)).toEqual(['Fresh claim']);});
 it('distinguishes proposed predictions and falsification from source findings',()=>{const cards=buildStudyCards(lenses[0],lenses[0].replay.proposer);expect(cards.some(c=>c.stage==='prediction'&&c.question.includes('proposed extension'))).toBe(true);expect(cards.some(c=>c.stage==='falsification')).toBe(true);});
 it('escapes Markdown content and disallows executable source URLs',()=>{expect(studyFilename('../../<script> Paper')).toBe('script-paper-flashcards.md');expect(safeUrl('javascript:alert(1)')).toBe('');const md=studyMarkdown('<script> *Hi*',[]);expect(md).toContain('&lt;script&gt;');expect(md).toContain('\\*Hi\\*');});
 it('returns weak cards to the queue until self-assessed as understood',()=>{let p={queue:['mechanism','prediction'],completed:0,revisits:0};p=advanceQuiz(p,true);expect(p.queue).toEqual(['prediction','mechanism']);p=advanceQuiz(p,false);p=advanceQuiz(p,false);expect(p).toEqual({queue:[],completed:2,revisits:1});});
 it('challenges overgeneralizations and asks for a baseline when discussing predictions',()=>{const card=buildStudyCards(lenses[0])[0];expect(followUp(card,'This always guarantees the correct result under every conceivable experimental condition')).toContain('counterexample');expect(followUp({...card,stage:'prediction'},'The output changes in response to the altered input after several steps')).toContain('baseline');});
});
