import { describe, it, expect } from 'vitest';
import { lenses } from '../src/data';
import { createWorkflow, inputHash, invalidateDescendants, topologicalOrder, validateConnection, WorkflowRunner } from '../src/workflow/runner';
import type { Artifact, ExecuteRequest, ExecuteResponse, WorkflowNode } from '../shared/contracts';
const fixture=lenses[0];
function opts(){return {...createWorkflow(),paper:fixture.paper,profile:fixture.profile,fixture,mode:'replay' as const};}
describe('DAG semantics',()=>{
 it('builds nine research and five understanding instruments without community search',()=>{for(const [kind,count] of [['research',9],['understand',5]] as const){const {nodes,edges}=createWorkflow(kind);expect(nodes).toHaveLength(count);expect(nodes.some(n=>n.type==='community')).toBe(false);expect(edges.some(e=>e.source==='community'||e.target==='community')).toBe(false);}});
 it('rejects legacy community execution without invoking any network request',async()=>{const o=opts();o.nodes.push({id:'community',type:'community',settings:{},status:'idle',inputHash:null,output:null,position:{x:0,y:0}});await expect(new WorkflowRunner().run(o)).rejects.toThrow('removed');});
 it('rejects cycles and incompatible artifacts',()=>{const {nodes,edges}=createWorkflow();expect(validateConnection(nodes,edges,'skeptic','paper').valid).toBe(false);expect(validateConnection(nodes,edges,'tutor','paper').valid).toBe(false);expect(()=>topologicalOrder(nodes,[...edges,{id:'cycle',source:'skeptic',target:'paper',sourcePort:'output',targetPort:'input'}])).toThrow('cycle');});
 it('only invalidates descendants after a demo setting edit',()=>{const {nodes,edges}=createWorkflow();const complete=nodes.map(n=>({...n,status:'complete' as const}));const result=invalidateDescendants(complete,edges,'demonstrator');expect(result.filter(n=>n.status==='stale').map(n=>n.id).sort()).toEqual(['collaborator','demonstrator','proposer','skeptic']);expect(result.find(n=>n.id==='reader')?.status).toBe('complete');});
 it('hashes canonical inputs independent of property order',async()=>{expect(await inputHash({a:1,b:{c:2}})).toBe(await inputHash({b:{c:2},a:1}));expect(await inputHash({a:1})).not.toBe(await inputHash({a:2}));});
 it.each(lenses)('completes the $id replay and reuses cached output',async(lens)=>{const runner=new WorkflowRunner();const events:string[]=[];const o={...createWorkflow(),paper:lens.paper,profile:lens.profile,fixture:lens,mode:'replay' as const};const first=await runner.run(o);expect(first.every(n=>n.status==='complete')).toBe(true);const second=await runner.run({...o,nodes:first,onEvent:e=>events.push(e.type)});expect(second.every(n=>n.status==='complete')).toBe(true);expect(events.filter(e=>e==='cache-hit')).toHaveLength(first.length);});
 it('rejects recorded inference against an unrelated pasted paper',async()=>{await expect(new WorkflowRunner().run({...opts(),paper:{...fixture.paper,id:'pasted'}})).rejects.toThrow('bundled');});
 it.each(['paper','reader','demonstrator','profile'])('runs the full prerequisite closure when starting fresh from %s',async(fromNodeId)=>{const result=await new WorkflowRunner().run({...opts(),fromNodeId});const requiredResults=['overlap','proposer','collaborator','skeptic'];for(const id of requiredResults)expect(result.find(n=>n.id===id)?.status).toBe('complete');});
 it.each(lenses)('does not reuse $id recorded critique for a different proposal',async(lens)=>{const runner=new WorkflowRunner();const o={...createWorkflow(),paper:lens.paper,profile:lens.profile,fixture:lens,mode:'replay' as const};const first=await runner.run(o);const speculative=lens.replay.proposer.proposals!.find(p=>p.kind==='speculative')!;const selected=first.map(n=>n.type==='skeptic'?{...n,settings:{selectedProposalId:speculative.id}}:n);const result=await runner.run({...o,nodes:selected,fromNodeId:'skeptic'});const critique=result.find(n=>n.type==='skeptic')!;expect(critique.status).toBe('error');expect(critique.error).toContain('no recorded assessment');});
 it('reruns only descendants when the demonstration changes',async()=>{const runner=new WorkflowRunner();const o=opts();const first=await runner.run(o);const edited=first.map(n=>n.id==='demonstrator'?{...n,settings:{parameters:{retention:0.7,steps:60,initial:1}}}:n);const running:string[]=[];const second=await runner.run({...o,nodes:edited,fromNodeId:'demonstrator',onEvent:e=>{if(e.type==='running')running.push(e.nodeId)}});expect(running.sort()).toEqual(['collaborator','demonstrator','proposer','skeptic']);expect(second.find(n=>n.id==='demonstrator')?.output?.demo?.parameters.retention).toBe(0.7);expect(second.find(n=>n.id==='reader')?.output).toEqual(first.find(n=>n.id==='reader')?.output);});
});
describe('bounded execution and cancellation',()=>{
 it('retains cancelled requests as unmeasured usage without guessing tokens',async()=>{let started!:()=>void;const ready=new Promise<void>(r=>{started=r});const usage={requests:0,inputTokens:0,outputTokens:0,unmeasuredRequests:0};const runner=new WorkflowRunner(async(_request,_code,signal)=>{started();return new Promise((_,reject)=>signal?.addEventListener('abort',()=>reject(new DOMException('Cancelled','AbortError')),{once:true}))});const running=runner.run({...opts(),mode:'live',onUsage:u=>{usage.requests+=u.requests;usage.inputTokens+=u.inputTokens;usage.outputTokens+=u.outputTokens;usage.unmeasuredRequests+=u.unmeasuredRequests??0}});await ready;runner.cancel();await running;expect(usage).toEqual({requests:1,inputTokens:0,outputTokens:0,unmeasuredRequests:1});});
 it('runs at most two live requests concurrently and respects dependency evidence',async()=>{let active=0,peak=0,count=0;const executor=async(req:ExecuteRequest):Promise<ExecuteResponse>=>{active++;peak=Math.max(peak,active);count++;if(req.type==='proposer')expect(Object.values(req.inputs).some(a=>a.connections)).toBe(true);await new Promise(r=>setTimeout(r,5));active--;return {output:fixture.replay[req.type],usage:{requests:1,inputTokens:10,outputTokens:5},model:'mock'};};const runner=new WorkflowRunner(executor);const nodes=await runner.run({...opts(),mode:'live'});expect(nodes.every(n=>n.status==='complete')).toBe(true);expect(peak).toBe(2);expect(count).toBe(7);});
 it('keeps the basic understanding journey to four model requests',async()=>{let calls=0;const runner=new WorkflowRunner(async(req)=>{calls++;return {output:fixture.replay[req.type],usage:{requests:1,inputTokens:0,outputTokens:0},model:'mock'};});await runner.run({...opts(),...createWorkflow('understand'),mode:'live'});expect(calls).toBe(4);});
 it('cancel prevents late results from overwriting a newer run',async()=>{let release:((value:ExecuteResponse)=>void)|undefined;let startedResolve:()=>void=()=>{};const started=new Promise<void>(r=>{startedResolve=r});const executor=async():Promise<ExecuteResponse>=>{startedResolve();return new Promise(r=>{release=r});};const runner=new WorkflowRunner(executor);let updates:WorkflowNode[][]=[];const old=runner.run({...opts(),mode:'live',onUpdate:n=>updates.push(n)});await started;runner.cancel();const fresh=await runner.run({...opts(),onUpdate:n=>updates.push(n)});const updateCount=updates.length;release!({output:{summary:'LATE WRONG RESULT'},usage:{requests:1,inputTokens:1,outputTokens:1},model:'mock'});await old;expect(updates.length).toBe(updateCount);expect(fresh.every(n=>n.status==='complete')).toBe(true);expect(updates.at(-1)?.some(n=>n.output?.summary==='LATE WRONG RESULT')).toBe(false);});
 it('errors leave upstream results usable and block dependent requests',async()=>{const runner=new WorkflowRunner(async()=>{throw new Error('Explicit transport failure');});const result=await runner.run({...opts(),mode:'live'});expect(result.find(n=>n.id==='paper')?.status).toBe('complete');expect(result.find(n=>n.id==='reader')?.status).toBe('error');expect(result.find(n=>n.id==='proposer')?.status).toBe('error');});
});
