import {test,expect} from '@playwright/test';
test('exports grounded Markdown and supports Socratic follow-up',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/Explore the Schmidhuber lens/}).click();
 await page.getByRole('button',{name:'Study & export',exact:true}).click();
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:/Export .*cards/}).click();const download=await pending;
 expect(download.suggestedFilename()).toMatch(/\.md$/);const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));const markdown=Buffer.concat(chunks).toString('utf8');expect(markdown).toContain('Q:');expect(markdown).toContain('A:');expect(markdown).toMatch(/PDF p/);
 await page.getByRole('button',{name:'Start Socratic practice'}).click();await page.getByLabel('Your reasoning',{exact:true}).fill('The forget gate controls retained state, so reducing it changes memory over time.');await page.getByRole('button',{name:'Explore my answer'}).click();await expect(page.getByLabel('Develop your explanation')).toBeVisible();await page.getByRole('button',{name:'Reveal source answer'}).click();await expect(page.getByRole('heading',{name:'Compare your reasoning'})).toBeVisible();
});
test('LSTM controls step real state and reset',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/Explore the Schmidhuber lens/}).click();await page.getByRole('button',{name:'LSTM lab',exact:true}).click();await expect(page.getByRole('heading',{name:'Inside an LSTM cell'})).toBeVisible();await page.getByRole('button',{name:'Step →',exact:true}).click();await expect(page.getByText(/STEP 2 \/ /)).toBeVisible();const gate=page.getByRole('slider').first();const before=await gate.inputValue();await gate.fill('0');expect(await gate.inputValue()).not.toBe(before);await page.getByRole('button',{name:'Reset lab'}).click();await expect(page.getByText(/STEP 1 \/ /)).toBeVisible();
});
test('RNA mechanism responds to target and catalytic activity',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/Explore the Hannon lens/}).click();await page.getByRole('button',{name:'RNA lab',exact:true}).click();await page.getByLabel('Target pairing').selectOption('mismatched');await page.getByLabel('Ago2 catalysis').selectOption('inactive');for(let i=0;i<3;i++)await page.getByRole('button',{name:'Next stage →'}).click();await expect(page.getByRole('button',{name:'Next stage →'})).toBeDisabled();await expect(page.locator('.rna-explanation')).toContainText(/cleavage|cleave|pair/i);await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.getByLabel('Target pairing')).toHaveValue('matched');
});
test('actual MuJoCo recording plays beside three policy explanations',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/Robotics lab/}).click();await expect(page.getByText('Recorded model rollout')).toBeVisible();await expect(page.getByRole('heading',{name:'ACT',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Diffusion',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'SmolVLA',exact:true})).toBeVisible();await page.getByRole('button',{name:'Play rollout'}).click();await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(0);await page.getByRole('button',{name:'Pause',exact:true}).click();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('Diffusion and SmolVLA recordings play with measured telemetry',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/Robotics lab/}).click();
 for(const policy of ['Diffusion','SmolVLA']){await page.getByRole('button',{name:`${policy} trajectory`,exact:true}).click();await expect(page.getByText('Recorded model rollout')).toBeVisible();await expect(page.locator('.robot-run')).toContainText('400');await page.getByRole('button',{name:'Play rollout',exact:true}).click();await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.1);await page.getByRole('button',{name:'Pause',exact:true}).click();await expect(page.locator('.robot-run')).toContainText('telemetry');await expect(page.locator('.robot-run')).toContainText('Not completed');}
});
