import {test,expect} from '@playwright/test';
for(const lens of ['Schmidhuber','Hannon'])test(`${lens} workflow and lab never request model generation`,async({page})=>{
 const modelCalls:string[]=[];await page.route('**/api/execute-node',r=>{modelCalls.push(r.request().url());return r.abort();});await page.route('**/api/explain-experiment',r=>{modelCalls.push(r.request().url());return r.abort();});
 await page.goto('/');await page.getByRole('button',{name:new RegExp(`Explore the ${lens} lens`)}).click();await expect(page.getByRole('button',{name:'Live',exact:true})).toHaveCount(0);await expect(page.getByLabel('Execution mode')).toHaveCount(0);await page.getByRole('button',{name:'Run workflow',exact:true}).click();await expect(page.getByText(/0?9 \/ 0?9 instruments complete/)).toBeVisible();
 await page.getByRole('button',{name:lens==='Hannon'?'RNA lab':'LSTM lab',exact:true}).click();await expect(page.getByRole('button',{name:'Explain this experiment',exact:true})).toHaveCount(0);await expect(page.getByRole('article',{name:'Generated experiment explanation'})).toBeVisible();await page.getByRole('slider').first().count().then(async n=>{if(n){await page.getByRole('slider').first().focus();await page.getByRole('slider').first().press('ArrowRight');}});expect(modelCalls).toEqual([]);
});
test('saved Live workspace restores into recorded-only mode',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/Explore the Schmidhuber lens/}).click();await page.getByRole('button',{name:'Run workflow',exact:true}).click();await expect(page.getByText(/0?9 \/ 0?9 instruments complete/)).toBeVisible();await page.evaluate(()=>{const key='marginalia-workspace-v1',data=JSON.parse(localStorage.getItem(key)!);data.mode='live';localStorage.setItem(key,JSON.stringify(data));});await page.reload();await page.getByRole('button',{name:/Resume (saved )?workspace/}).click();await expect(page.getByRole('button',{name:'Live',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('marginalia-workspace-v1')!).mode)).toBe('replay');
});
