import { useEffect, useMemo, useRef, useState } from 'react';
import { Background, Controls, ReactFlow, applyNodeChanges, type Node, type ReactFlowInstance } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import type { Artifact, LensFixture } from '../../shared/contracts';
import { AutoresearchRunner, STAGES, STAGE_LABELS, canConnectStage, defaultLoopConfig, loopFingerprint, readyForLive, restoreLoop, serializeLoop, validateLoop, type LoopConfig, type LoopRound, type LoopSnapshot, type StageKind } from '../autoresearch';
import { Evidence } from './Artifacts';
import '../autoresearch.css';

type Props={lens:LensFixture;mode:'replay'|'live';demoCode:string;inputs:Record<string,Artifact>;onClose:()=>void;onChat?:()=>void};
const stageDescriptions:Record<StageKind,string>={objective:'Set the question and budget',propose:'Generate a testable hypothesis',critique:'Check evidence and falsifiability',revise:'Feed critique into the next round'};
function RoundResult({round,lens}:{round:LoopRound;lens:LensFixture}){
 const proposal=round.proposal.proposals?.find(p=>p.id===round.selectedId);const critique=round.critique.critique;if(!proposal)return null;
 return <article className="auto-round"><header><span className="auto-pixel">Round {round.number.toString().padStart(2,'0')}</span><span className={`auto-verdict ${critique?.verdict}`}>{critique?.verdict}</span></header><h3>{proposal.title}</h3><p>{proposal.hypothesis}</p><dl><dt>Change</dt><dd>{proposal.change}</dd><dt>Baseline</dt><dd>{proposal.baseline}</dd><dt>Ablation</dt><dd>{proposal.ablation}</dd><dt>Metric</dt><dd>{proposal.metric}</dd></dl><details><summary>What would falsify this?</summary><p>{proposal.falsificationCriterion}</p></details><details><summary>Mechanism & experiment</summary><pre>{proposal.formulation}</pre><p>{proposal.minimalExperiment}</p><ul>{proposal.resources.map((r,i)=><li key={i}>{r}</li>)}</ul></details><details><summary>Critique & evidence</summary>{critique&&(['supported','assumptions','unsupported','suggestedChanges'] as const).map(key=><section key={key}><h4>{key==='suggestedChanges'?'Next revision':key}</h4><ul>{critique[key].map((text,i)=><li key={i}>{text}</li>)}</ul></section>)}<Evidence refs={proposal.evidenceRefs} lens={lens}/><h4>Open questions</h4><ul>{proposal.noveltyQuestions.map((q,i)=><li key={i}>{q}</li>)}</ul></details></article>;
}
export default function AutoresearchLab(props:Props){return <RecordedAutoresearchLab {...props} mode="replay"/>;}
function RecordedAutoresearchLab({lens,mode,demoCode,inputs,onClose,onChat}:Props){
 const storageKey=`marginalia-autoresearch-v1:${lens.paper.id}:${mode}`;
 const initial=useMemo(()=>{try{return restoreLoop(localStorage.getItem(storageKey));}catch{return null;}},[storageKey]);
 const [config,setConfig]=useState<LoopConfig>(initial?.config??defaultLoopConfig);
 const [snapshot,setSnapshot]=useState<LoopSnapshot|null>(initial?.snapshot??null);
 const [selected,setSelected]=useState<StageKind>('objective');const [message,setMessage]=useState('');const [storageError,setStorageError]=useState(false);
 const dialog=useRef<HTMLDivElement|null>(null);const flow=useRef<Pick<ReactFlowInstance,'screenToFlowPosition'>|null>(null);const runner=useRef(new AutoresearchRunner());const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;const previous=document.activeElement as HTMLElement|null;dialog.current?.focus();return()=>{mounted.current=false;runner.current.cancel();previous?.focus();};},[]);
 useEffect(()=>{runner.current.cancel();setConfig(initial?.config??defaultLoopConfig());setSnapshot(initial?.snapshot??null);setMessage('');},[initial]);
 useEffect(()=>{try{localStorage.setItem(storageKey,serializeLoop(config,snapshot));setStorageError(false);}catch{setStorageError(true);}},[storageKey,config,snapshot]);
 const active=snapshot?.status==='running';const invalid=validateLoop(config);const fingerprint=loopFingerprint(lens,inputs,config,mode);const changed=!!snapshot&&snapshot.fingerprint!==fingerprint;
 const canResume=!!snapshot&&!changed&&['paused','error'].includes(snapshot.status)&&snapshot.dispatches<8;
 const notReady=mode==='live'&&!readyForLive(lens,inputs);const missingCode=mode==='live'&&!demoCode;
 const nodes:Node[]=config.stages.map(stage=>({id:stage.id,position:stage.position,sourcePosition:'right' as Node['sourcePosition'],targetPosition:'left' as Node['targetPosition'],selected:stage.id===selected,className:`auto-stage ${active&&((snapshot?.phase==='critique'&&stage.id==='critique')||(snapshot?.phase==='propose'&&stage.id===(snapshot.rounds.length?'revise':'propose')))?'auto-stage-running':''}`,style:{width:175},data:{label:<><span className="auto-pixel">{String(STAGES.indexOf(stage.id)+1).padStart(2,'0')}</span><strong>{STAGE_LABELS[stage.id]}</strong><small>{stageDescriptions[stage.id]}</small></>}}));
 const update=(patch:Partial<LoopConfig>)=>{if(!active){setConfig(current=>({...current,...patch}));setMessage('');}};
 function addStage(id:StageKind,position?:{x:number;y:number}){if(active)return;if(config.stages.some(s=>s.id===id)){setSelected(id);setMessage(`${STAGE_LABELS[id]} is already on the canvas.`);return;}update({stages:[...config.stages,{id,position:position??{x:35+STAGES.indexOf(id)*215,y:75}}]});setSelected(id);}
 async function run(resume=false){setMessage('');try{await runner.current.run({lens,inputs,config,mode,demoCode,snapshot:resume?snapshot:null,onUpdate:value=>{if(mounted.current)setSnapshot(value);}});}catch(error){setMessage(error instanceof Error?error.message:'Could not start the research loop.');}}
 function close(){runner.current.cancel();onClose();}
 return <div className="auto-lab" role="dialog" aria-modal="true" aria-labelledby="auto-title"><div className="auto-shell" ref={dialog} tabIndex={-1} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();close();}if(event.key==='Tab'){const items=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), summary, a[href], [tabindex="0"]');const visible=Array.from(items??[]).filter(item=>item.getClientRects().length);const first=visible[0],last=visible.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}}><header className="auto-heading"><div><span className="auto-pixel">Marginalia / Research systems</span><h1 id="auto-title">Autoresearch loop</h1><p>{lens.label} · {mode==='live'?'Live generation':'Recorded review'}</p></div><div>{onChat&&<button onClick={onChat}>Ask tutor</button>} <button onClick={close} aria-label="Close autoresearch loop">Close ×</button></div></header>
 <div className="auto-toolbar"><div><strong>{mode==='live'?`${config.rounds} rounds · up to ${config.rounds*2} model calls`:'1 recorded review · 0 model calls'}</strong><small>Propose → critique → revise. One request at a time.</small></div><div className="auto-actions">{active?<button className="primary" onClick={()=>runner.current.cancel()}>Pause loop</button>:<><button className="primary" disabled={!!invalid||notReady||missingCode||(mode==='replay'&&config.kind!=='incremental')} onClick={()=>void run(false)}>{snapshot?'Start new loop':'Run loop'}</button>{canResume&&<button onClick={()=>void run(true)}>Resume saved loop</button>}</>}</div></div>
 <div className="auto-layout"><aside className="auto-palette"><h2>Instruments</h2><p>Drag onto the canvas, or click to add.</p>{STAGES.map(id=><button key={id} draggable={!active} disabled={active} onDragStart={event=>{event.dataTransfer.setData('application/marginalia-stage',id);event.dataTransfer.effectAllowed='move';}} onClick={()=>addStage(id)}><span className="auto-pixel">+ {STAGE_LABELS[id]}</span><small>{stageDescriptions[id]}</small></button>)}<button disabled={active} onClick={()=>{update({stages:defaultLoopConfig().stages,edges:defaultLoopConfig().edges});}}>Build example loop</button><button disabled={active} onClick={()=>update({stages:[],edges:[]})}>Clear canvas</button></aside>
 <div className="auto-canvas" aria-label="Research loop graph" onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='move';}} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData('application/marginalia-stage');if(STAGES.includes(id as StageKind))addStage(id as StageKind,flow.current?.screenToFlowPosition({x:event.clientX,y:event.clientY}));}}><ReactFlow nodes={nodes} edges={config.edges.map(e=>({...e,type:'smoothstep',animated:false}))} onInit={instance=>{flow.current=instance;}} onNodeClick={(_event,node)=>setSelected(node.id as StageKind)} onNodesChange={changes=>{if(active)return;const next=applyNodeChanges(changes,nodes);setConfig(current=>({...current,stages:next.map(n=>({id:n.id as StageKind,position:n.position})),edges:current.edges.filter(e=>next.some(n=>n.id===e.source)&&next.some(n=>n.id===e.target))}));}} onEdgesDelete={edges=>{if(!active)update({edges:config.edges.filter(e=>!edges.some(deleted=>deleted.id===e.id))});}} onConnect={connection=>{if(active||!connection.source||!connection.target)return;if(canConnectStage(config,connection.source,connection.target))update({edges:[...config.edges,{id:`${connection.source}-${connection.target}`,source:connection.source as StageKind,target:connection.target as StageKind}]});else setMessage('Connect neighboring stages in order: Objective → Propose → Critique → Revise.');}} nodesDraggable={!active} nodesConnectable={!active} elementsSelectable={!active} deleteKeyCode={active?null:['Backspace','Delete']} fitView fitViewOptions={{padding:.2}} minZoom={.3} maxZoom={1.5} snapToGrid snapGrid={[15,15]}><Background gap={15} size={1}/><Controls showInteractive={false}/></ReactFlow></div>
 <aside className="auto-settings"><h2>{STAGE_LABELS[selected]}</h2><p>{stageDescriptions[selected]}</p><label htmlFor="auto-objective">Research objective</label><textarea id="auto-objective" value={config.objective} maxLength={1600} rows={4} disabled={active} onChange={e=>update({objective:e.target.value})}/><label htmlFor="auto-kind">Hypothesis track</label><select id="auto-kind" value={config.kind} disabled={active||mode==='replay'} onChange={e=>update({kind:e.target.value as LoopConfig['kind']})}><option value="incremental">Incremental</option><option value="cross-field">Cross-field</option><option value="speculative">Speculative</option></select><label htmlFor="auto-rounds">Maximum rounds</label><input id="auto-rounds" type="number" min={1} max={3} value={config.rounds} disabled={active||mode==='replay'} onChange={e=>update({rounds:Number(e.target.value)})}/><label className="auto-check"><input type="checkbox" checked={config.stopOnSupported} disabled={active||mode==='replay'} onChange={e=>update({stopOnSupported:e.target.checked})}/>Stop if the critic returns “supported”</label><button disabled={active||!config.stages.some(s=>s.id===selected)} onClick={()=>update({stages:config.stages.filter(s=>s.id!==selected),edges:config.edges.filter(e=>e.source!==selected&&e.target!==selected)})}>Remove selected instrument</button><details><summary>Wire without dragging</summary>{STAGES.slice(1).map((target,index)=>{const source=STAGES[index];const connected=config.edges.some(e=>e.source===source&&e.target===target);return <button key={target} disabled={active||(!connected&&!canConnectStage(config,source,target))} onClick={()=>update({edges:connected?config.edges.filter(e=>!(e.source===source&&e.target===target)):[...config.edges,{id:`${source}-${target}`,source,target}]})}>{connected?'Disconnect':'Connect'} {STAGE_LABELS[source]} → {STAGE_LABELS[target]}</button>;})}</details></aside></div>
 <div className="auto-notices" aria-live="polite">{invalid&&<p>{invalid}</p>}{notReady&&<p>Complete Reader and Research Overlap in the Live workspace first.</p>}{missingCode&&<p>Enter your Live access code in the workspace.</p>}{changed&&<p>Settings or evidence changed. Start a new loop to apply them.</p>}{message&&<p role="alert">{message}</p>}{storageError&&<p>Browser storage is full or unavailable. This loop cannot be restored after closing.</p>}{snapshot?.stopReason&&<p>{snapshot.stopReason.replace(' Live mode generates revisions.','')}</p>}{active&&<p>Round {snapshot.rounds.length+1} / {config.rounds} · {snapshot.phase==='critique'?'Checking selected hypothesis':snapshot.rounds.length?'Revising from critique':'Generating hypotheses'}…</p>}</div>
 {snapshot&&<section className="auto-results" aria-label="Research loop results"><div className="auto-usage"><strong>{snapshot.rounds.length} completed {snapshot.rounds.length===1?'round':'rounds'}</strong><span>{snapshot.usage.requests} requests · {snapshot.usage.inputTokens.toLocaleString()} input / {snapshot.usage.outputTokens.toLocaleString()} output tokens{snapshot.usage.unmeasuredRequests?` · ${snapshot.usage.unmeasuredRequests} unmeasured`:''}</span></div>{snapshot.pending&&<p>Proposal saved. {snapshot.status==='running'?'Critique is running.':'Resume to run its critique.'}</p>}{snapshot.rounds.map(round=><RoundResult key={`${snapshot.runId}-${round.number}`} round={round} lens={lens}/>)}</section>}
 <footer className="auto-footer">Saved in this browser. Closing the page pauses orchestration.<details><summary>Execution details</summary><p>This recorded loop shows the selected paper, a research hypothesis and its critique. Moving and connecting instruments updates the saved configuration. Replaying the review makes no model request.</p>{mode==='replay'&&<p>The recorded review uses the bundled incremental proposal and its authored critique. Changing the objective saves your configuration; it does not rewrite the recorded text.</p>}</details></footer>
 </div></div>;
}
