import {useEffect,useMemo,useRef,useState} from 'react';
import {GO_COLUMNS,goCoordinate,replayGoGame,type GoGame,type GoPosition} from '../go';
import '../go-games.css';
interface GameCollection{version:number;retrievedAt:string;archiveUrl:string;archiveSha256:string;matchSourceUrl:string;normalization:string;games:GoGame[];}
const side=(color:'B'|'W')=>color==='B'?'Black':'White';
function winner(game:GoGame){return game.result.startsWith('B+')?game.black:game.result.startsWith('W+')?game.white:'Result unavailable';}
function Board({position,numbers,game}:{position:GoPosition;numbers:boolean;game:GoGame}){
 const last=position.lastMove;const lastIndex=last?.x!==null&&last?.x!==undefined?last.y!*position.size+last.x:-1;
 return <svg className="go-board" viewBox="0 0 600 600" role="img" aria-label={`Game ${game.number}, move ${position.move} of ${game.moves.length}${last?`. ${side(last.color)} ${goCoordinate(last)}`:'. Empty board'}`}><rect x="0" y="0" width="600" height="600" fill="#d9b579"/><rect x="11" y="11" width="578" height="578" fill="none" stroke="#8b673c" strokeWidth="2"/>{Array.from({length:19},(_,i)=><g key={i}><line x1="48" y1={48+28*i} x2="552" y2={48+28*i} stroke="#685032" strokeWidth="1"/><line x1={48+28*i} y1="48" x2={48+28*i} y2="552" stroke="#685032" strokeWidth="1"/>{[25,577].map(y=><text key={`x${y}`} x={48+28*i} y={y} textAnchor="middle" dominantBaseline="central" fill="#392d22" fontSize="11" fontFamily="monospace">{GO_COLUMNS[i]}</text>)}{[25,577].map(x=><text key={`y${x}`} x={x} y={48+28*i} textAnchor="middle" dominantBaseline="central" fill="#392d22" fontSize="11" fontFamily="monospace">{19-i}</text>)}</g>)}{[3,9,15].flatMap(y=>[3,9,15].map(x=><circle key={`${x}-${y}`} cx={48+28*x} cy={48+28*y} r="3.1" fill="#493723"/>))}{position.stones.map((stone,index)=>{if(!stone)return null;const x=48+28*(index%19),y=48+28*Math.floor(index/19),lastMove=index===lastIndex;return <g key={index}><circle cx={x+1.5} cy={y+1.5} r="12.4" fill="#6d5839"/><circle cx={x} cy={y} r="12.2" fill={stone.color==='B'?'#152035':'#f4f1e6'} stroke={lastMove?'#d44c3f':stone.color==='B'?'#080e1c':'#99998d'} strokeWidth={lastMove?2.5:1.2}/>{numbers?<text x={x} y={y+.6} textAnchor="middle" dominantBaseline="central" fontFamily="monospace" fontWeight="700" fontSize={stone.moveNumber>=100?8.2:10} fill={stone.color==='B'?'#f0efe7':'#1c2940'}>{stone.moveNumber}</text>:lastMove?<rect x={x-3} y={y-3} width="6" height="6" fill={stone.color==='B'?'#f0bd6a':'#c7493b'}/>:null}</g>;})}</svg>;
}
export default function GoGames(){
 const [collection,setCollection]=useState<GameCollection|null>(null);const [error,setError]=useState('');const [reload,setReload]=useState(0);const [index,setIndex]=useState(0);const [cursor,setCursor]=useState(0);const [playing,setPlaying]=useState(false);const [numbers,setNumbers]=useState(false);const [speed,setSpeed]=useState(650);const list=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const abort=new AbortController();setError('');fetch('/alphago/games.json',{signal:abort.signal}).then(async response=>{if(!response.ok)throw new Error('The game records could not be loaded.');const data=await response.json() as GameCollection;if(data.version!==1||!Array.isArray(data.games)||data.games.length!==5)throw new Error('The game collection is incomplete.');for(const game of data.games){if(game.size!==19||!game.moves.length)throw new Error('An invalid game record was received.');replayGoGame(game);}if(!abort.signal.aborted)setCollection(data);}).catch(reason=>{if(!abort.signal.aborted)setError(reason instanceof Error?reason.message:'Could not load the games.');});return()=>abort.abort();},[reload]);
 const game=collection?.games[index];const positions=useMemo(()=>game?replayGoGame(game):[],[game]);const position=positions[cursor];
 useEffect(()=>{if(!playing||!game)return;const timer=window.setInterval(()=>setCursor(current=>{if(current>=game.moves.length){setPlaying(false);return current;}return current+1;}),speed);return()=>window.clearInterval(timer);},[playing,game,speed]);
 useEffect(()=>{if(cursor===game?.moves.length)setPlaying(false);const active=list.current?.querySelector<HTMLElement>(`[data-go-move="${cursor}"]`);if(active&&list.current)list.current.scrollTop=active.offsetTop-list.current.offsetTop-list.current.clientHeight/2+active.offsetHeight/2;},[cursor,game]);
 const jump=(number:number,move=0)=>{setPlaying(false);setIndex(number-1);setCursor(move);};
 const seek=(move:number)=>{setPlaying(false);setCursor(Math.max(0,Math.min(game?.moves.length??0,move)));};
 if(error)return <section className="go-games"><h2>Lee Sedol match</h2><p role="alert">{error}</p><button onClick={()=>setReload(value=>value+1)}>Reload game records</button></section>;
 if(!collection||!game||!position)return <section className="go-games"><h2>Lee Sedol match</h2><p role="status">Loading five game records…</p></section>;
 return <section className="go-games" aria-label="AlphaGo versus Lee Sedol game replays"><header className="go-heading"><div><span className="go-kicker">Seoul / March 2016</span><h2>Five games. Every move.</h2><p>AlphaGo 4 · Lee Sedol 1</p></div><a href={game.downloadUrl} download>Download game {game.number} SGF ↓</a></header><nav className="go-game-selector" aria-label="Select match game">{collection.games.map(g=><button key={g.id} aria-pressed={game.id===g.id} onClick={()=>jump(g.number)}><span>GAME {g.number}</span><strong>{winner(g)}</strong><small>{g.date.slice(5)} · resignation</small></button>)}</nav><div className="go-highlights"><button onClick={()=>jump(2,37)}>AlphaGo · Game 2, move 37 ↗</button><button onClick={()=>jump(4,78)}>Lee Sedol · Game 4, move 78 ↗</button></div>
 <div className="go-replay-layout"><div className="go-board-column"><Board position={position} numbers={numbers} game={game}/><div className="go-timeline"><label htmlFor="go-move-slider">Move <output>{cursor} / {game.moves.length}</output></label><input id="go-move-slider" aria-label="Game move" type="range" min={0} max={game.moves.length} step={1} value={cursor} onChange={event=>seek(Number(event.target.value))}/></div><div className="go-playback"><button aria-label="Reset game to start" onClick={()=>seek(0)} disabled={cursor===0}>|←</button><button aria-label="Previous Go move" onClick={()=>seek(cursor-1)} disabled={cursor===0}>←</button><button className="go-play" onClick={()=>{if(cursor===game.moves.length)setCursor(0);setPlaying(value=>!value);}}>{playing?'Pause game':'Play game'}</button><button aria-label="Next Go move" onClick={()=>seek(cursor+1)} disabled={cursor===game.moves.length}>→</button><button aria-label="Go to final move" onClick={()=>seek(game.moves.length)} disabled={cursor===game.moves.length}>→|</button></div><div className="go-options"><label><input type="checkbox" checked={numbers} onChange={event=>setNumbers(event.target.checked)}/> Move numbers</label><label>Playback speed<select value={speed} onChange={event=>setSpeed(Number(event.target.value))}><option value={1200}>Slow</option><option value={650}>Normal</option><option value={250}>Fast</option></select></label></div></div>
 <aside className="go-game-info"><div className="go-match-title"><span className="go-kicker">Game {game.number} · {game.date}</span><h3>{winner(game)} wins</h3><span>By resignation · {game.moves.length} moves</span></div><div className="go-player"><i className="go-black-stone"/><div><strong>{game.black}</strong><span>Black · {position.captures.B} captured</span></div></div><div className="go-player"><i className="go-white-stone"/><div><strong>{game.white}</strong><span>White · {position.captures.W} captured</span></div></div><div className="go-current" aria-live="polite"><span className="go-kicker">{cursor===0?'Opening position':`Move ${cursor}`}</span><strong>{position.lastMove?`${side(position.lastMove.color)} ${goCoordinate(position.lastMove)}`:'Black to play'}</strong><span>{cursor===game.moves.length?'End of recorded game':`${side(position.nextColor)} plays next`}</span></div>{game.number===2&&cursor===37&&<p className="go-moment">AlphaGo’s move 37: the black stone at P10.</p>}{game.number===4&&cursor===78&&<p className="go-moment">Lee Sedol’s move 78: the white stone at L11.</p>}<h4 className="go-kicker">Move record</h4><div className="go-move-list" ref={list} aria-label="Move record">{game.moves.map((move,i)=><button key={i} data-go-move={i+1} aria-current={cursor===i+1?'step':undefined} aria-label={`Go to move ${i+1}, ${side(move.color)} ${goCoordinate(move)}`} onClick={()=>seek(i+1)}><span>{String(i+1).padStart(3,'0')}</span><i className={move.color==='B'?'go-black-stone':'go-white-stone'}/><strong>{goCoordinate(move)}</strong></button>)}</div><p className="go-rules">{game.rules} rules · {game.komi} komi</p></aside></div>
 <details className="go-sources"><summary>Sources & game records</summary><p>Match result and highlighted moves: <a href={collection.matchSourceUrl} target="_blank" rel="noreferrer">Google DeepMind</a>. Move records: <a href={collection.archiveUrl} target="_blank" rel="noreferrer">AlphaGo Games SGF archive</a>. Retrieved {collection.retrievedAt.slice(0,10)}.</p><p>Downloads contain the played main line and game metadata. Commentary and alternative variations were removed. Captures are computed from the recorded moves; the displayed match result comes from the record. The player supplies no position evaluation or win probability.</p><a href="/alphago/games.json" download>Download normalized records and SHA-256 checksums</a></details></section>;
}
