import {useEffect,useRef,useState} from 'react';
import '../world.css';
import '../world-brush.css';
import JapaneseBrushHouse, {BrushGarden, BrushTree} from './JapaneseBrushHouse';
export type HouseId='schmidhuber'|'hannon'|'robotics'|'alphago';
const houses:Array<{id:HouseId;name:string;topic:string;x:number;y:number;color:string;symbol:string;access:string}>=[
 {id:'schmidhuber',name:'MEMORY HOUSE',topic:'Schmidhuber · LSTM',x:215,y:195,color:'var(--world-memory)',symbol:'∞',access:'Explore the Schmidhuber lens'},
 {id:'hannon',name:'RNA HOUSE',topic:'Hannon · RNA interference',x:785,y:195,color:'var(--world-rna)',symbol:'⌁',access:'Explore the Hannon lens'},
 {id:'robotics',name:'ROBOTICS WORKSHOP',topic:'ACT · Diffusion · SmolVLA',x:215,y:480,color:'var(--world-robotics)',symbol:'⊞',access:'Robotics lab · LeRobot × MuJoCo'},
 {id:'alphago',name:'ALPHAGO HOUSE',topic:'Search · Networks · Five games',x:785,y:480,color:'var(--world-alphago)',symbol:'●',access:'Explore AlphaGo'},
];
const start={x:500,y:460};
function PixelTree({x,y,size=1}:{x:number;y:number;size?:number}){return <g transform={`translate(${x} ${y}) scale(${size})`}><path d="M-5 0H5V24H-5Z" fill="var(--world-pixel-4)"/><path d="M-10-42H10V-32H21V-20H29V0H17V9H-17V0H-29V-20H-21V-32H-10Z" fill="var(--world-pixel-5)"/><path d="M-9-38H9V-28H17V-17H-3V-7H-20V-20H-14V-28H-9Z" fill="var(--world-pixel-6)"/><path d="M13-15H24V-2H13Z" fill="var(--world-pixel-7)"/></g>}
function House({house,build=1}:{house:typeof houses[number];build?:number}){const {x,y,color,symbol}=house;return <g transform={`translate(${x} ${y})`} className="world-building" style={{'--house-color':color} as React.CSSProperties}>
 <path d="M-108 18H108V33H-108Z" fill="var(--world-pixel-8)"/>
 <g opacity={build>=.15?1:.35}><path d="M-92-15H92V22H-92Z" fill="var(--world-pixel-9)"/><path d="M-101 12H101V24H-101Z" fill="var(--world-pixel-10)"/></g>
 {build>=.3&&<g><path d="M-88-85H88V12H-88Z" fill="var(--world-pixel-11)" stroke="var(--world-pixel-12)" strokeWidth="4"/><path d="M-82-78H-73V10H-82ZM73-78H82V10H73Z" fill="var(--world-pixel-13)"/><path d="M-80-47H80M-80-13H80" stroke="var(--world-pixel-14)" strokeWidth="3"/></g>}
 {build>=.5&&<g><path d="M-110-83H-98V-98H-74V-112H-49V-126H49V-112H74V-98H98V-83H110V-73H-110Z" fill={color}/><path d="M-96-85H96V-76H-96ZM-74-99H74V-94H-74ZM-48-113H48V-108H-48Z" fill="var(--world-pixel-15)" opacity=".45"/><path d="M51-144H68V-105H51Z" fill="var(--world-pixel-16)"/></g>}
 {build>=.7&&<g><path d="M-66-54H-38V-22H-66ZM38-54H66V-22H38Z" fill={color}/><path d="M-52-54V-22M-66-39H-38M52-54V-22M38-39H66" stroke="var(--world-pixel-17)" strokeWidth="4"/><path d="M-20-48H20V14H-20Z" fill="var(--world-pixel-18)" stroke="var(--world-pixel-19)" strokeWidth="3"/><path d="M11-16H15V-10H11Z" fill="var(--world-pixel-3)"/></g>}
 {build>=.9&&<g><rect x="-21" y="-105" width="42" height="24" fill="var(--world-pixel-20)"/><text x="0" y="-87" textAnchor="middle" fill={color} fontSize="21">{symbol}</text><path d="M-28 15H28V21H-28ZM-35 21H35V28H-35Z" fill="var(--world-pixel-21)"/></g>}
 {build<1&&<g className="world-construction"><path d="M-115 15V-115M115 15V-115M-115-60H115M-115-25H115" stroke="var(--world-pixel-22)" strokeWidth="5"/><rect x="-125" y="24" width="35" height="18" fill="var(--world-pixel-3)"/><rect x="90" y="24" width="35" height="18" fill="var(--world-pixel-3)"/><path d="M-122 25L-106 42M-106 25L-90 42M91 25L108 42M108 25L123 42" stroke="var(--world-pixel-20)" strokeWidth="5"/></g>}
 </g>}
export default function KnowledgeWorld({onEnter,onChat,onAddPaper,onResume,resumable}:{onEnter:(id:HouseId)=>void;onChat:()=>void;onAddPaper:()=>void;onResume:()=>void;resumable:boolean}){
 const [theme,setTheme]=useState<'pixel'|'brush'>('pixel');
 useEffect(()=>{try{setTheme(localStorage.getItem('marginalia-world-theme')==='brush'?'brush':'pixel')}catch{/* Storage may be unavailable. */}},[]);
 const chooseTheme=(value:'pixel'|'brush')=>{setTheme(value);try{localStorage.setItem('marginalia-world-theme',value)}catch{/* Keep the theme for this visit. */}};
 const [position,setPosition]=useState(start);const pos=useRef(start);const [walking,setWalking]=useState(false);const [destination,setDestination]=useState<HouseId|null>(null);const path=useRef<Array<{x:number;y:number}>>([]);const target=useRef<HouseId|null>(null);const [build,setBuild]=useState(0);const progress=useRef(build);useEffect(()=>{try{if(sessionStorage.getItem('marginalia-alphago-built')==='yes'){progress.current=1;setBuild(1)}}catch{/* Keep local progress. */}},[]);const constructing=useRef(false);const keys=useRef(new Set<string>());const [near,setNear]=useState<HouseId|null>(null);const enter=useRef(onEnter);enter.current=onEnter;
 const travel=(id:HouseId)=>{const h=houses.find(h=>h.id===id);if(!h)return;keys.current.clear();target.current=id;setDestination(id);const road=h.y<300?270:560;const corridor=h.x<500?410:590;path.current=[{x:corridor,y:pos.current.y},{x:corridor,y:road},{x:h.x,y:road},{x:h.x,y:h.y+53}];if(id==='alphago')constructing.current=true;};
 useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0,last=0;const tick=(now:number)=>{const dt=Math.min((now-last)/1000||0,.05);last=now;let p=pos.current,moving=false;
  const dx=(keys.current.has('arrowright')||keys.current.has('d')?1:0)-(keys.current.has('arrowleft')||keys.current.has('a')?1:0);const dy=(keys.current.has('arrowdown')||keys.current.has('s')?1:0)-(keys.current.has('arrowup')||keys.current.has('w')?1:0);
  if(dx||dy){path.current=[];target.current=null;const d=Math.hypot(dx,dy);const n={x:Math.max(45,Math.min(955,p.x+dx/d*180*dt)),y:Math.max(70,Math.min(625,p.y+dy/d*180*dt))};const blocked=houses.some(h=>Math.abs(n.x-h.x)<100&&n.y>h.y-118&&n.y<h.y+30)||(n.x>453&&n.x<547&&n.y>307&&n.y<390);if(!blocked){p=n;moving=true;}}
  else if(path.current.length){const n=path.current[0],dist=Math.hypot(n.x-p.x,n.y-p.y),stride=220*dt;if(dist<=stride){p=n;path.current.shift()}else {p={x:p.x+(n.x-p.x)/dist*stride,y:p.y+(n.y-p.y)/dist*stride};}moving=true;}
  if(p.x>570&&p.y>350)constructing.current=true;
  if(constructing.current&&progress.current<1){progress.current=Math.min(1,progress.current+(reduced?1:dt/2.8));setBuild(progress.current);if(progress.current===1)try{sessionStorage.setItem('marginalia-alphago-built','yes')}catch{/* Keep local progress. */}}
  if(p!==pos.current){pos.current=p;setPosition(p);}setWalking(moving);
  const h=houses.find(h=>Math.hypot(p.x-h.x,p.y-(h.y+53))<48);setNear(h?.id??null);
  if(!path.current.length&&target.current&&h?.id===target.current&&(h.id!=='alphago'||progress.current===1)){const id=target.current;target.current=null;enter.current(id);}
  frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
 },[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,button,a,summary,[contenteditable=true]'))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){e.preventDefault();keys.current.add(k);setDestination(null)}if(k==='enter'&&near&&(near!=='alphago'||progress.current===1)){e.preventDefault();onEnter(near)}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());const blur=()=>keys.current.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur)}},[near,onEnter]);
 return <main className="knowledge-world" data-theme={theme}><header className="world-header"><div><span className="world-kicker">KNOWLEDGE WORLD</span><h1>Marginalia<span>.</span></h1></div><div className="world-header-actions"><div className="world-theme-switch" role="group" aria-label="World theme"><button type="button" aria-pressed={theme==='pixel'} onClick={()=>chooseTheme('pixel')}>Pixel</button><button type="button" aria-pressed={theme==='brush'} onClick={()=>chooseTheme('brush')}>Brush &amp; ink</button></div>{resumable&&<button onClick={onResume}>Resume workspace</button>}<button onClick={onAddPaper}>Add paper text +</button></div></header><div className="world-intro"><p>Read the paper. <span>Move the ideas.</span></p><span>WASD / arrows to walk · choose a house to travel</span></div>
 <div className="world-map" tabIndex={0} aria-label="Walkable knowledge world. Use arrow keys or WASD, or choose a destination below.">
 <svg className="world-scene" viewBox="0 0 1000 680" role="img" aria-label="Four knowledge houses around Schmidhuber plaza" shapeRendering={theme==='pixel'?'crispEdges':'geometricPrecision'}><defs><filter id="world-dry-brush" x="-10%" y="-15%" width="120%" height="130%"><feTurbulence type="fractalNoise" baseFrequency=".09" numOctaves="2" seed="17" result="grain"/><feDisplacementMap in="SourceGraphic" in2="grain" scale="1.8" xChannelSelector="R" yChannelSelector="G"/></filter><pattern id="world-paper-grain" width="77" height="61" patternUnits="userSpaceOnUse"><path d="M4 11l16 1m14 19l22-1M9 48l11-2m42 4l9 1M57 8l8 1" stroke="var(--world-wood-light)" strokeWidth=".7" opacity=".45"/><path d="M20 17l1 4m26 23l-1 3" stroke="var(--world-paper)" strokeWidth="2"/></pattern><pattern id="grass" width="52" height="44" patternUnits="userSpaceOnUse"><rect width="52" height="44" fill="var(--world-pixel-23)"/><path d="M7 12H10V15H7ZM35 34H38V37H35ZM29 5H31V8H29Z" fill="var(--world-pixel-24)"/></pattern><pattern id="path" width="24" height="20" patternUnits="userSpaceOnUse"><rect width="24" height="20" fill="var(--world-pixel-25)"/><path d="M0 0H24V2H0ZM11 2H13V20H11Z" fill="var(--world-pixel-26)"/></pattern></defs>
 {theme==='brush'?<BrushGarden/>:<g><rect width="1000" height="680" fill="url(#grass)"/><path d="M0 290H1000V305H0ZM465 0H535V680H465Z" fill="var(--world-pixel-27)"/><path d="M187 244H813V285H187ZM187 534H813V575H187ZM477 244H523V575H477Z" fill="url(#path)"/><path d="M193 210H237V275H193ZM763 210H807V275H763ZM193 500H237V560H193ZM763 500H807V560H763Z" fill="url(#path)"/>
 <path d="M425 300H575V420H425Z" fill="var(--world-pixel-28)"/><path d="M431 306H569V414H431Z" fill="var(--world-pixel-29)"/><path d="M439 314H561V406H439Z" fill="var(--world-pixel-30)"/>
 </g>}
 {[{x:72,y:110},{x:343,y:88},{x:645,y:94},{x:922,y:98},{x:91,y:388},{x:353,y:360},{x:660,y:351},{x:933,y:393},{x:80,y:618},{x:349,y:615},{x:650,y:616},{x:924,y:620}].map((p,i)=>theme==='brush'?<BrushTree key={i} {...p} size={i%2?0.8:1}/>:<PixelTree key={i} {...p} size={i%2?0.8:1}/>)}
 <g fill="var(--world-pixel-31)">{Array.from({length:24},(_,i)=><path key={i} d={`M${40+(i*137)%925} ${30+(i*79)%620}h4v4h-4z`}/>)}</g>
 {houses.map(h=>theme==='brush'?<JapaneseBrushHouse key={h.id} x={h.x} y={h.y} symbol={h.symbol} build={h.id==='alphago'?build:1}/>:<House key={h.id} house={h} build={h.id==='alphago'?build:1}/>)}
 <g transform="translate(500 350)"><path d="M-44 26H44V38H-44ZM-53 38H53V46H-53Z" fill="var(--world-pixel-32)"/><image href="/world/schmidhuber-pixel.png" x="-58" y="-66" width="116" height="116" preserveAspectRatio="xMidYMid meet"/><rect x="-59" y="50" width="118" height="20" fill="var(--world-pixel-33)"/><text x="0" y="64" textAnchor="middle" fill="var(--world-pixel-3)" fontSize="10" fontFamily="monospace">SCHMIDHUBER PLAZA</text></g>
 <g transform={`translate(${Math.round(position.x)} ${Math.round(position.y)})`} className={walking?'world-avatar walking':'world-avatar'}><path d="M-10 3H12V9H-10Z" fill="var(--world-pixel-34)" opacity=".6"/><g className="avatar-body"><path d="M-7-25H7V-19H-7Z" fill="var(--world-pixel-35)"/><path d="M-8-19H8V-9H-8Z" fill="var(--world-pixel-36)"/><path d="M-9-9H9V2H-9Z" fill="var(--world-pixel-3)"/><path d="M-12-6H-9V2H-12ZM9-6H12V2H9Z" fill="var(--world-pixel-36)"/><path d="M-7 2H-1V9H-7ZM2 2H8V9H2Z" fill="var(--world-pixel-37)"/></g></g>
 </svg>
 <button className="world-portrait-hit" aria-label="Chat with the Socratic tutor" onClick={onChat}><span>Ask a question</span></button>
 {houses.map(h=><button key={h.id} className={`world-house-label ${destination===h.id?'destination':''}`} style={{left:`${h.x/10}%`,top:`${(h.y+50)/6.8}%`}} onClick={()=>travel(h.id)} aria-label={h.access}><strong>{h.name}</strong><span>{h.topic}</span></button>)}
 <div className="world-map-status" aria-live="polite">{destination?`Walking to ${houses.find(h=>h.id===destination)?.name.toLowerCase()}…`:near?'Press Enter to enter':'Choose a house.'}{build>0&&build<1&&<span>AlphaGo house · {Math.round(build*100)}%</span>}</div>
 </div><nav className="world-destinations" aria-label="Knowledge houses">{houses.map((h,i)=><button key={h.id} onClick={()=>travel(h.id)} style={{'--house-color':h.color} as React.CSSProperties}><small>0{i+1}</small><strong>{h.name}</strong><span>{h.topic}</span><b>Walk there →</b></button>)}</nav><div className="world-footer"><button onClick={onChat}>Socratic tutor ↗</button><span>Move with arrows · Enter a house · WASD to walk</span><button onClick={()=>{try{sessionStorage.removeItem('marginalia-alphago-built')}catch{/* Keep local progress. */}keys.current.clear();setNear(null);setWalking(false);progress.current=0;constructing.current=false;setBuild(0);pos.current=start;setPosition(start);path.current=[];target.current=null;setDestination(null)}}>Reset walk</button></div>
 </main>
}
