import {useEffect,useRef,useState} from 'react';
import type {PaperDocument,Usage} from '../../shared/contracts';
import type {SocraticMessage,SocraticOutput} from '../../shared/socratic';
import {socraticChat,SocraticApiError} from '../socratic-api';
import '../socratic.css';
import TutorText from './TutorText';
type Message=SocraticMessage&{output?:SocraticOutput;documents?:PaperDocument[]};
const ZERO:Usage={requests:0,inputTokens:0,outputTokens:0,unmeasuredRequests:0};
export default function SocraticChat({documents,topic,demoCode,onDemoCodeChange,onClose}:{documents:PaperDocument[];topic:string;demoCode:string;onDemoCodeChange:(code:string)=>void;onClose:()=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[usage,setUsage]=useState<Usage>(ZERO),[configured,setConfigured]=useState<boolean|null>(null),[codeNeeded,setCodeNeeded]=useState(!demoCode),[selection,setSelection]=useState('all');
 const epoch=useRef(0),controller=useRef<AbortController|null>(null),mounted=useRef(true),runId=useRef(crypto.randomUUID()),scroll=useRef<HTMLDivElement>(null);
 const sourceDocuments=documents.filter((d,i,a)=>a.findIndex(v=>v.id===d.id)===i).slice(0,4);
 const selectedDocuments=selection==='general'?[]:selection==='all'?sourceDocuments:sourceDocuments.filter(d=>d.id===selection);
 const selectedTopic=selection==='general'?'General mathematics, learning and games':selection==='all'?topic:(selectedDocuments[0]?.title??topic);
 useEffect(()=>{mounted.current=true;const abort=new AbortController();fetch('/api/health',{signal:abort.signal}).then(r=>r.json()).then(v=>{if(mounted.current)setConfigured(!!v.configured);}).catch(()=>{if(mounted.current&&!abort.signal.aborted)setNotice('Backend status unavailable. Check your local server.');});return()=>{mounted.current=false;epoch.current++;controller.current?.abort();abort.abort();};},[]);
 useEffect(()=>{scroll.current?.scrollIntoView({block:'nearest',behavior:'auto'});},[messages,pending]);
 function stop(){epoch.current++;controller.current?.abort();controller.current=null;setPending(false);setNotice('Stopped. In-flight usage may remain unmeasured.');}
 function reset(nextSelection=selection){epoch.current++;controller.current?.abort();controller.current=null;runId.current=crypto.randomUUID();setMessages([]);setDraft('');setPending(false);setError('');setNotice('');setUsage(ZERO);setSelection(nextSelection);}
 function settle(value:Usage){if(mounted.current)setUsage(old=>({requests:old.requests+value.requests-1,inputTokens:old.inputTokens+value.inputTokens,outputTokens:old.outputTokens+value.outputTokens,unmeasuredRequests:(old.unmeasuredRequests??0)+(value.unmeasuredRequests??0)-1}));}
 async function send(){
  const text=draft.trim();if(!text||pending||!demoCode||configured===false||usage.requests>=8)return;
  const id=++epoch.current,abort=new AbortController();controller.current=abort;setPending(true);setError('');setNotice('');setDraft('');
  const history=messages.slice(-12).map(({role,content})=>({role,content:content.slice(0,4000)}));setMessages(old=>[...old,{role:'user',content:text}]);setUsage(old=>({...old,requests:old.requests+1,unmeasuredRequests:(old.unmeasuredRequests??0)+1}));
  try{const result=await socraticChat({runId:runId.current,topic:selectedTopic.slice(0,200),documents:selectedDocuments,history,userMessage:text},demoCode,abort.signal);if(mounted.current&&id===epoch.current){settle(result.usage);setCodeNeeded(false);setMessages(old=>[...old,{role:'assistant',content:result.output.reply,output:result.output,documents:selectedDocuments}]);}}
  catch(e){if(mounted.current&&id===epoch.current){if(e instanceof SocraticApiError){settle(e.usage??ZERO);if(e.status===401)setCodeNeeded(true);}if(!abort.signal.aborted){setError(e instanceof Error?e.message:'Unable to reach the tutor.');setDraft(text);}}}
  finally{if(mounted.current&&id===epoch.current){setPending(false);controller.current=null;}}
 }
 const starterQuestions=/RNA|Hannon|Dicer|Argonaute/i.test(selectedTopic)?['Help me separate guide production from target cleavage.','Quiz me on the role of Ago2.','What experiment would falsify this mechanism?']:/Go|game/i.test(selectedTopic)?['Help me understand policy versus value in Go.','Quiz me on Monte Carlo tree search.','Explain how self-play improves a policy.']:/Robot|ACT|Diffusion|SmolVLA/i.test(selectedTopic)?['How does the action chunk horizon affect stability?','Quiz me on temporal ensembling.','How does diffusion differ from flow matching?']:['Help me understand how an LSTM preserves memory.','Quiz me on the forget gate.','Explain one equation from this paper.'];
 const suggestions=messages.at(-1)?.output?.suggestedQuestions??starterQuestions;
 return <section className="socratic-chat" aria-label="Socratic tutor"><header className="socratic-header"><img src="/world/schmidhuber-pixel.png" alt="Pixel portrait of Jürgen Schmidhuber"/><div><span className="socratic-kicker">CONSOLIDATE / QUESTION / UNDERSTAND</span><h2>Socratic tutor</h2><p>An AI research tutor. One idea, one question at a time.</p></div><button onClick={onClose} aria-label="Close tutor">×</button></header>
 <div className="socratic-toolbar"><label>Study context<select aria-label="Tutor study context" value={selection} onChange={e=>reset(e.target.value)}><option value="all">{topic}</option>{sourceDocuments.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}<option value="general">General concepts · no paper sources</option></select></label><button onClick={()=>reset()}>New conversation</button></div>
 {(codeNeeded||!demoCode)&&<label className="socratic-code">Live access code<input type="password" autoComplete="off" value={demoCode} onChange={e=>onDemoCodeChange(e.target.value)} placeholder="Demo access code"/><small>Stored only for this session. Never enter an API key here.</small></label>}
 {configured===false&&<p className="socratic-notice">Live tutoring needs OPENAI_API_KEY and DEMO_CODE on the server.</p>}
 <div className="socratic-messages" role="log" aria-label="Tutor conversation" aria-live="polite">{!messages.length&&<div className="socratic-welcome"><h3>Bring a question. Build an explanation.</h3><p>Tell me what you understand so far, or choose a starting point below.</p></div>}{messages.map((m,i)=><article key={i} className={`socratic-message ${m.role}`}><strong>{m.role==='user'?'You':'Tutor'}</strong><div className="socratic-prose"><TutorText text={m.content}/></div>{!!m.output?.evidenceRefs.length&&<details><summary>Sources · {m.output.evidenceRefs.length}</summary>{m.output.evidenceRefs.map((ref,j)=>{const d=m.documents?.find(x=>x.id===ref.documentId),p=d?.passages.find(x=>x.id===ref.passageId);return <section key={j}><a href={d?.sourceUrl} target="_blank" rel="noreferrer">{d?.title??ref.documentId}{p?.page?` · PDF p. ${p.page}`:''}</a><blockquote>{ref.supportingExcerpt}</blockquote></section>;})}</details>}</article>)}{pending&&<p className="socratic-thinking">Reading your question…</p>}<div ref={scroll}/></div>
 {!pending&&<div className="socratic-suggestions">{suggestions.map(q=><button key={q} onClick={()=>setDraft(q)}>{q}</button>)}</div>}
 {error&&<p role="alert" className="socratic-error">{error}</p>}{notice&&<p className="socratic-notice">{notice}</p>}
 <form className="socratic-compose" onSubmit={e=>{e.preventDefault();void send();}}><label htmlFor="socratic-question">Your question or answer</label><textarea id="socratic-question" rows={3} maxLength={2000} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Here is what I understand so far…"/><div><span>Live · OpenAI API</span>{pending?<button type="button" onClick={stop}>Stop response</button>:<button type="submit" className="primary" disabled={!draft.trim()||!demoCode||configured===false||usage.requests>=8}>Send to tutor</button>}</div></form>
 {usage.requests>=8&&<p className="socratic-notice">This conversation reached its eight-request limit. Start a new conversation to continue.</p>}<footer className="socratic-usage">{usage.requests} / 8 requests · {usage.inputTokens.toLocaleString()} input / {usage.outputTokens.toLocaleString()} output tokens{usage.unmeasuredRequests?` · ${usage.unmeasuredRequests} unmeasured`:''}</footer></section>;
}
