import { useMemo, useState } from 'react';
import type { Artifact, LensFixture } from '../../shared/contracts';
import { advanceQuiz, buildStudyCards, followUp, safeUrl, studyFilename, studyMarkdown, type QuizProgress } from '../study';
import '../study.css';
export function StudyPanel({lens,artifact,onClose}:{lens:LensFixture;artifact?:Artifact;onClose:()=>void}) {
 const cards=useMemo(()=>buildStudyCards(lens,artifact),[lens,artifact]);
 const [mode,setMode]=useState<'cards'|'quiz'>('cards');const [selected,setSelected]=useState(()=>new Set(cards.map(c=>c.id)));
 const [progress,setProgress]=useState<QuizProgress>({queue:[],completed:0,revisits:0});const [answer,setAnswer]=useState('');const [submitted,setSubmitted]=useState(false);const [hint,setHint]=useState(0);const [reveal,setReveal]=useState(false);const [exported,setExported]=useState(false);
 const active=cards.find(c=>c.id===progress.queue[0]);const chosen=cards.filter(c=>selected.has(c.id));
 function resetQuestion(){setAnswer('');setSubmitted(false);setHint(0);setReveal(false);}
 function start(){setProgress({queue:chosen.map(c=>c.id),completed:0,revisits:0});resetQuestion();setMode('quiz');}
 function next(revisit:boolean){setProgress(p=>advanceQuiz(p,revisit));resetQuestion();}
 function download(){const blob=new Blob([studyMarkdown(lens.paper.title,chosen)],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=studyFilename(lens.paper.title);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExported(true);}
 return <section className="study-panel" aria-label="Study desk"><header><div><span className="eyebrow">Study desk</span><h2>Consolidate</h2><p>{lens.paper.title}</p></div><button onClick={onClose} aria-label="Close study desk">Close ×</button></header><nav aria-label="Study mode"><button aria-pressed={mode==='cards'} onClick={()=>setMode('cards')}>Q&A cards</button><button disabled={!chosen.length} onClick={start}>Start Socratic practice</button></nav>{mode==='cards'?<><div className="study-actions"><button disabled={!chosen.length} onClick={download}>Export {chosen.length} cards · .md</button><button onClick={()=>setSelected(new Set(cards.map(c=>c.id)))}>Select all</button><button onClick={()=>setSelected(new Set())}>Clear</button></div><p role="status">{exported?'Markdown export prepared.':`${chosen.length} of ${cards.length} selected`}</p>{cards.map((c,i)=><article className="study-card" key={c.id}><label><input type="checkbox" checked={selected.has(c.id)} onChange={e=>{const checked=e.target.checked;setSelected(old=>{const n=new Set(old);if(checked)n.add(c.id);else n.delete(c.id);return n;});}}/><span>{i+1}. {c.question}</span></label><details><summary>Answer & sources</summary><p className="study-answer">{c.answer}</p>{c.sources.map((s,j)=><a key={j} href={safeUrl(s.url)} target="_blank" rel="noreferrer">{s.label}</a>)}</details></article>)}</>:active?<article className="study-question"><span className="eyebrow">{active.stage} · {progress.queue.length} remaining</span><h3>{active.question}</h3><label htmlFor="study-answer">Your reasoning</label><textarea id="study-answer" value={answer} onChange={e=>setAnswer(e.target.value)} rows={5}/><div className="study-actions"><button disabled={!answer.trim()} onClick={()=>setSubmitted(true)}>Explore my answer</button><button disabled={hint>=2} onClick={()=>setHint(h=>h+1)}>Hint {Math.min(hint+1,2)}</button><button onClick={()=>setReveal(true)}>Reveal source answer</button></div>{hint>0&&<p className="study-prompt">Start with {active.sources[0]?.label}. Identify the variables and how they are connected.</p>}{hint>1&&<blockquote>{active.sources[0]?.text}</blockquote>}{submitted&&<div className="study-prompt" role="status"><small>Guided practice · self-assessed</small><p>{followUp(active,answer)}</p><label htmlFor="study-followup">Develop your explanation</label><textarea id="study-followup" rows={3}/></div>}{reveal&&<div className="study-answer"><h4>Compare your reasoning</h4><p>{active.answer}</p>{active.sources.map((s,i)=><a key={i} href={safeUrl(s.url)} target="_blank" rel="noreferrer">{s.label}</a>)}<div className="study-actions"><button onClick={()=>next(false)}>Understood · next</button><button onClick={()=>next(true)}>Revisit this card</button></div></div>}</article>:<div role="status"><h3>Practice complete</h3><p>{progress.completed} cards consolidated · {progress.revisits} revisits</p><button onClick={start}>Practice again</button></div>}</section>;
}
