import {useMemo,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {MathBlock} from './MathBlock';
import {diffusionExample} from '../../math/diffusion';
export default function DiffusionMath(){
 const [steps,setSteps]=useState(40),[beta,setBeta]=useState(.15),[seed,setSeed]=useState(7),[iteration,setIteration]=useState(0),[target,setTarget]=useState(.7),[execute,setExecute]=useState(8);
 const data=useMemo(()=>diffusionExample(steps,beta,seed,target),[steps,beta,seed,target]);
 const shown=data.states[Math.min(iteration,steps)];
 const chart=shown.action.map((value,i)=>({time:i,action:value,target:data.clean[i],execute:i<execute?value:undefined}));
 const s=data.schedule[Math.max(0,shown.k-1)];
 return <div className="architecture-math">
 <section className="math-section"><h3>01 / Predict a distribution of action chunks</h3><p>The policy conditions a temporal U-Net on recent camera features and joint positions. An action chunk contains H future actions, each with d robot coordinates. Robot time t and denoising iteration k are different axes.</p><MathBlock tex={String.raw`O_t=(o_{t-T_o+1},\ldots,o_t),\quad A_t^0\in\mathbb R^{H\times d},\quad \epsilon_\theta(A_t^k,k,O_t)\in\mathbb R^{H\times d}`} label="O: observation history; H: prediction horizon; d: action dimension; θ: learned weights."/><MathBlock tex={String.raw`c=\operatorname{concat}_{j}(\operatorname{ResNet}(I_j),s_j),\qquad h'=\gamma(c,k)\odot\operatorname{GroupNorm}(h)+b(c,k)`} label="Visual and state conditioning modulate the temporal U-Net with FiLM; skip connections preserve temporal detail."/><MathBlock tex={String.raw`h_{\ell+1}=\operatorname{Down}(\operatorname{ResBlock}(h_\ell;c,k)),\quad u_\ell=\operatorname{ResBlock}(\operatorname{concat}(\operatorname{Up}(u_{\ell+1}),h_\ell);c,k)`} label="1D convolutions mix neighbouring action times. Downsampling expands temporal context; upsampling and skip concatenation recover a noise estimate at every action index."/><MathBlock tex={String.raw`\nabla_{A^k}\log p_k(A^k\mid O)\approx-\frac{\epsilon_\theta(A^k,k,O)}{\sqrt{1-\bar\alpha_k}}`} label="The noise predictor also parameterizes a conditional score: a direction towards higher-density action chunks."/></section>
 <section className="math-section"><h3>02 / Train by corrupting demonstrated actions</h3><MathBlock tex={String.raw`\alpha_k=1-\beta_k,\quad\bar\alpha_k=\prod_{j=1}^k\alpha_j,\qquad A^k=\sqrt{\bar\alpha_k}A^0+\sqrt{1-\bar\alpha_k}\epsilon,\quad\epsilon\sim\mathcal N(0,I)`}/><MathBlock tex={String.raw`\mathcal L(\theta)=\mathbb E_{(O,A^0),k,\epsilon}\left[\|\epsilon-\epsilon_\theta(A^k,k,O)\|_2^2\right]`} label="Sample a demonstration, a noise level and Gaussian noise; learn to predict the injected noise."/></section>
 <section className="math-section"><h3>03 / Reverse the noise, one step at a time</h3><MathBlock tex={String.raw`A^{k-1}=\frac1{\sqrt{\alpha_k}}\left(A^k-\frac{\beta_k}{\sqrt{1-\bar\alpha_k}}\epsilon_\theta(A^k,k,O)\right)+\sqrt{\tilde\beta_k}z,\quad \tilde\beta_k=\beta_k\frac{1-\bar\alpha_{k-1}}{1-\bar\alpha_k}`} label="z is standard Gaussian noise. At k = 1, posterior variance is zero. Inference starts from Gaussian noise at k = K."/>
 <div className="math-controls">
 <label>Noise steps K: {steps}<input aria-label="Diffusion noise steps" type="range" min="10" max="100" step="10" value={steps} onChange={e=>{setSteps(+e.target.value);setIteration(0);}}/></label>
 <label>Final β: {beta.toFixed(2)}<input aria-label="Diffusion final beta" type="range" min="0.02" max="0.3" step="0.01" value={beta} onChange={e=>setBeta(+e.target.value)}/></label>
 <label>Conditioned target: {target.toFixed(2)}<input aria-label="Diffusion target" type="range" min="-1" max="1" step=".05" value={target} onChange={e=>setTarget(+e.target.value)}/></label>
 <label>Noise seed<input aria-label="Diffusion seed" type="number" min="0" max="1000" value={seed} onChange={e=>setSeed(Math.max(0,Math.min(1000,+e.target.value)))}/></label>
 <label>Reverse steps completed: {Math.min(iteration,steps)} / {steps}<input aria-label="Diffusion denoising progress" type="range" min="0" max={steps} value={Math.min(iteration,steps)} onChange={e=>setIteration(+e.target.value)}/></label>
 <button onClick={()=>setIteration(i=>Math.min(steps,i+1))} disabled={iteration>=steps}>Denoise one step</button><button onClick={()=>setIteration(0)}>Reset noise</button>
 </div>
 <div style={{height:260}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" label={{value:'Action index within chunk',position:'insideBottom',offset:-2}}/><YAxis/><Tooltip/><Line name="Clean target" dataKey="target" stroke="#789b69" strokeDasharray="5 3" dot={false}/><Line name={`A at noise level ${shown.k}`} dataKey="action" stroke="#a46188" dot={false}/><Line name="Executed prefix" dataKey="execute" stroke="#e8ad59" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div>
 <p>Noise level k = {shown.k}. {shown.k?`Signal fraction ᾱ = ${s.alphaBar.toFixed(4)}; posterior variance = ${s.variance.toFixed(4)}.`:'The oracle has recovered the clean chunk.'}</p>
 <details><summary>Worked example construction</summary><p>This interactive calculation uses one action coordinate and an exact noise oracle derived from the displayed clean target. It starts from the exact forward-noised chunk, uses a linear β schedule and does not clip. The recorded pretrained trajectory uses a learned U-Net, Gaussian initialization, its saved scheduler and all 14 coordinates. The oracle isolates the equations; it does not predict the model’s accuracy.</p><MathBlock tex={String.raw`\epsilon_{\mathrm{oracle}}(A^k,k)=\frac{A^k-\sqrt{\bar\alpha_k}A^0}{\sqrt{1-\bar\alpha_k}}`}/></details></section>
 <section className="math-section"><h3>04 / Execute a prefix, observe again</h3><label>Actions executed before replanning: {execute}<input aria-label="Diffusion executed prefix" type="range" min="1" max="15" value={execute} onChange={e=>setExecute(+e.target.value)}/></label><MathBlock tex={String.raw`A_t^K\rightarrow\cdots\rightarrow A_t^0,\qquad a_t,\ldots,a_{t+T_a-1}\leftarrow A_t^0,\qquad O_{t+T_a}\rightarrow\text{replan}`} label="Tₐ is the execution horizon. Denoising K times produces one chunk; it does not advance the robot K times."/><p>Short prefixes react more often to new observations but require more inference. LeRobot aligns its predicted sequence to the first observation and starts execution at index Tₒ − 1.</p></section>
 <p><a href="https://diffusion-policy.cs.columbia.edu/" target="_blank" rel="noreferrer">Diffusion Policy · Chi et al.</a> · <a href="https://github.com/huggingface/lerobot/blob/main/src/lerobot/policies/diffusion/modeling_diffusion.py" target="_blank" rel="noreferrer">LeRobot implementation</a></p>
 </div>;
}
