import {useState} from 'react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {MathBlock} from './MathBlock';
import {analyticFlow,interpolateFlow,targetVelocity,maskedSoftmax,smolMask} from '../../math/smolvla';
export default function SmolVlaMath(){
 const [steps,setSteps]=useState(10),[condition,setCondition]=useState(1),[noise,setNoise]=useState(-1),[s,setS]=useState(.5),[query,setQuery]=useState(3);
 const rows=analyticFlow(noise,condition,steps),last=rows.at(-1)!;const labels=['Image','Language','State','Action 1','Action 2'];const attention=maskedSoftmax([.8,condition, .4,.2,-.1],smolMask(query));
 return <article className="architecture-math"><section className="math-section"><h3>01 · Pixels, language, state → context</h3><p>Image patches pass through a vision encoder and projection. Tokenized instructions and a projected proprioceptive state join the visual tokens. The VLM supplies keys and values to an action expert, whose layers alternate cross-attention to context and self-attention between action positions.</p><MathBlock tex={'C=[P_vE_v(I);E_l(\\ell);W_s s_{robot}],\\quad Q=HW_Q,\\ K=CW_K,\\ V=CW_V'} label="Context C combines image I, instruction ℓ and robot state; H holds action features."/><MathBlock tex={'\\operatorname{Attn}(Q,K,V)=\\operatorname{softmax}(QK^\\top/\\sqrt{d}+M)V'} label="d is key dimension. Mask M is 0 for allowed keys and −∞ otherwise."/><div className="math-controls"><label>Query token <select value={query} onChange={e=>setQuery(+e.target.value)}>{labels.map((v,i)=><option value={i} key={v}>{v}</option>)}</select></label></div><div className="math-grid">{labels.map((v,i)=><div className="math-card" key={v}><strong>{v}</strong><p>{smolMask(query)[i]?`${(100*attention[i]).toFixed(1)}%`:'Masked'}</p><progress max={1} value={attention[i]}/></div>)}</div><p>Fixed toy logits show the prefix visibility rule: image/language cannot read state or actions; state can read the prefix; action tokens can read context and one another. Cross-attention layers use context keys; self-attention layers also mix action tokens. Padding keys are excluded.</p></section>
 <section className="math-section"><h3>02 · Learn a continuous velocity field</h3><p>Let A be a normalized action chunk of H steps and dₐ coordinates; ε is Gaussian noise of the same shape. A sampled time chooses a point between noise and training actions. The network predicts a velocity at that point, conditioned on context.</p><MathBlock tex={'x_s=(1-s)\\epsilon+sA,\\quad u_s=A-\\epsilon,\\quad \\mathcal L=\\mathbb E_{A,\\epsilon,s}\\|v_\\theta(x_s,s,C)-(A-\\epsilon)\\|_2^2'} label="Noise→data convention: s=0 is noise; s=1 is action. LeRobot uses t=1−s, target ε−A and negative integration steps."/><div className="math-controls"><label>Interpolation s = {s.toFixed(2)}<input aria-label="SmolVLA interpolation time" type="range" min="0" max="1" step=".01" value={s} onChange={e=>setS(+e.target.value)}/></label><label>Noise ε = {noise.toFixed(1)}<input aria-label="SmolVLA noise" type="range" min="-2" max="2" step=".1" value={noise} onChange={e=>setNoise(+e.target.value)}/></label><label>Conditioned target = {condition.toFixed(1)}<input aria-label="SmolVLA conditioning" type="range" min="-2" max="2" step=".1" value={condition} onChange={e=>setCondition(+e.target.value)}/></label></div><p>Scalar training pair: xₛ = <strong>{interpolateFlow(noise,condition,s).toFixed(3)}</strong>; target velocity = <strong>{targetVelocity(noise,condition).toFixed(3)}</strong>. A straight paired path has constant target velocity; learned conditional fields need not be straight.</p></section>
 <section className="math-section"><h3>03 · Integrate, unnormalize, execute a chunk</h3><MathBlock tex={'x_{s+\\Delta s}=x_s+\\Delta s\\,v_\\theta(x_s,s,C),\\quad \\Delta s=1/N;\\qquad a=\\sigma_a\\odot x_1+\\mu_a'} label="N Euler steps transport an entire action chunk simultaneously; saved dataset statistics restore physical action units."/><p>Unlike DDPM's discrete noise schedule and noise-prediction reverse updates, SmolVLA learns a continuous flow velocity and solves its ODE. At deployment the policy executes the configured first action steps, then observes again.</p><label>Euler steps N = {steps}<input aria-label="SmolVLA Euler steps" type="range" min="2" max="64" step="1" value={steps} onChange={e=>setSteps(+e.target.value)}/></label><MathBlock tex={'\\dot x=2(c-x),\\quad x(0)=\\epsilon,\\quad x(s)=c+(\\epsilon-c)e^{-2s}'} label="Analytic teaching field with conditioning c; independent of the pretrained model."/><ResponsiveContainer width="100%" height={250}><LineChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="s" type="number" domain={[0,1]} tickFormatter={v=>Number(v).toFixed(1)}/><YAxis domain={[-2,2]}/><Tooltip/><Legend/><Line name="Euler approximation" dataKey="euler" stroke="#ffcd72" dot={false}/><Line name="Exact solution" dataKey="exact" stroke="#68d9d2" dot={false} strokeDasharray="4 3"/></LineChart></ResponsiveContainer><p>Endpoint integration error: <strong>{Math.abs(last.euler-last.exact).toFixed(6)}</strong>. Increasing N reduces discretization error for this field; it does not guarantee a better learned policy.</p></section><p><a href="https://arxiv.org/abs/2506.01844" target="_blank" rel="noreferrer">SmolVLA paper</a> · <a href="https://github.com/huggingface/lerobot/blob/main/src/lerobot/policies/smolvla/modeling_smolvla.py" target="_blank" rel="noreferrer">LeRobot implementation</a></p></article>;
}
