import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/stix-two-text/400.css';
import '@fontsource/stix-two-text/500.css';
import '@fontsource/stix-two-text/600.css';
import '@fontsource/stix-two-text/400-italic.css';
import '@xyflow/react/dist/style.css';
import 'katex/dist/katex.min.css';
import './styles.css';
import App from './App';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
